import type { SeedResourceType, SeedTopic, SeedUser } from "./seed-types";

export const seedResourceTypes: SeedResourceType[] = [
  { slug: "paper", name: "Paper", pluralName: "Papers", icon: "file-text", accent: "rose", description: "Peer-reviewed and preprint research.", isPrimaryNav: true },
  { slug: "course", name: "Course", pluralName: "Courses", icon: "graduation-cap", accent: "emerald", description: "Structured, multi-lesson programmes.", isPrimaryNav: true },
  { slug: "github", name: "GitHub", pluralName: "GitHub Repos", icon: "github", accent: "slate", description: "Open-source implementations and frameworks.", isPrimaryNav: true },
  { slug: "blog", name: "Blog", pluralName: "Blogs", icon: "pen-line", accent: "amber", description: "Deep-dive articles and engineering write-ups.", isPrimaryNav: true },
  { slug: "video", name: "Video", pluralName: "Videos", icon: "play", accent: "red", description: "Talks, lectures and recorded walkthroughs.", isPrimaryNav: true },
  { slug: "book", name: "Book", pluralName: "Books", icon: "book-open", accent: "indigo", description: "Long-form, edited treatments of a subject.", isPrimaryNav: true },
  { slug: "tutorial", name: "Tutorial", pluralName: "Tutorials", icon: "list-checks", accent: "violet", description: "Hands-on, build-along guides.", isPrimaryNav: true },
  { slug: "tool", name: "Tool", pluralName: "Tools", icon: "wrench", accent: "cyan", description: "Libraries and utilities you run yourself.", isPrimaryNav: true },
  { slug: "documentation", name: "Docs", pluralName: "Documentation", icon: "book-marked", accent: "sky", description: "Official reference material." },
  { slug: "dataset", name: "Dataset", pluralName: "Datasets", icon: "database", accent: "teal", description: "Training and evaluation corpora." },
  { slug: "benchmark", name: "Benchmark", pluralName: "Benchmarks", icon: "gauge", accent: "orange", description: "Leaderboards and evaluation suites." },
  { slug: "newsletter", name: "Newsletter", pluralName: "Newsletters", icon: "mail", accent: "fuchsia", description: "Recurring curated briefings." },
  { slug: "podcast", name: "Podcast", pluralName: "Podcasts", icon: "mic", accent: "purple", description: "Long-form audio conversations." },
  { slug: "ai-product", name: "AI Product", pluralName: "AI Products", icon: "sparkles", accent: "blue", description: "Shipped products worth studying." },
];

export const seedTopics: SeedTopic[] = [
  // ── Level 1 ────────────────────────────────────────────────────────────────
  {
    slug: "ai-fundamentals",
    name: "AI Fundamentals",
    tagline: "The maths and machine learning underneath everything else",
    description:
      "Neural networks, backpropagation, optimisation and the classical machine learning ideas that modern AI is built on. Start here if the rest of the map feels like it is written in a language you do not speak yet.",
    icon: "graduation-cap",
    accent: "emerald",
    isFeatured: true,
    related: ["llm", "ai-research"],
  },
  {
    slug: "llm",
    name: "Large Language Models",
    shortName: "LLM",
    tagline: "Everything about large language models: architecture, pre-training, fine-tuning, alignment, inference and more",
    description:
      "Large language models are the centre of gravity of modern AI. This topic covers how they are built (architecture and pre-training), how they are shaped (fine-tuning and alignment), how they are made fast (inference), and how we know whether any of it worked (evaluation).",
    icon: "sparkles",
    accent: "indigo",
    isFeatured: true,
    related: ["agents", "rag", "ai-engineering", "ai-research"],
  },
  {
    slug: "ai-engineering",
    name: "AI Engineering",
    tagline: "Infra, tools and MLOps for shipping AI systems",
    description:
      "The discipline of turning a model into a product that survives real traffic: serving, evaluation harnesses, observability, guardrails, cost control and the operational habits that keep an AI feature working after launch.",
    icon: "box",
    accent: "violet",
    isFeatured: true,
    related: ["llm", "rag", "agents", "ai-infrastructure"],
  },
  {
    slug: "agents",
    name: "Agents",
    tagline: "AI agents, tool use and multi-agent systems",
    description:
      "Systems where a model decides what to do next: tool calling, planning, memory, multi-agent coordination, and the evaluation problem that makes all of it hard to trust in production.",
    icon: "bot",
    accent: "emerald",
    isFeatured: true,
    related: ["llm", "ai-engineering", "ai-coding", "reasoning"],
  },
  {
    slug: "rag",
    name: "Retrieval Augmented Generation",
    shortName: "RAG",
    tagline: "Grounding language models in your own data",
    description:
      "Retrieval augmented generation connects a model to a corpus it was never trained on. Chunking, embeddings, hybrid retrieval, reranking and the evaluation practices that separate a demo from a system people trust.",
    icon: "database",
    accent: "amber",
    isFeatured: true,
    related: ["llm", "ai-engineering", "agents"],
  },
  {
    slug: "ai-coding",
    name: "AI Coding",
    tagline: "AI for developers: assistants, agents and code review",
    description:
      "How AI is changing software engineering: completion and chat assistants, autonomous coding agents, review automation, and the benchmarks used to measure whether any of them actually help.",
    icon: "code",
    accent: "sky",
    isFeatured: true,
    related: ["agents", "llm", "ai-engineering"],
  },
  {
    slug: "multimodal",
    name: "Multimodal",
    tagline: "Vision, audio and video models",
    description:
      "Models that work across modalities: vision-language models, diffusion-based generation, speech recognition and synthesis, and the architectures that let one model read an image and write about it.",
    icon: "image",
    accent: "teal",
    isFeatured: true,
    related: ["computer-vision", "llm", "ai-research"],
  },
  {
    slug: "computer-vision",
    name: "Computer Vision",
    tagline: "Perception: detection, segmentation and representation",
    description: "Classical and modern computer vision, from convolutional networks to vision transformers and open-vocabulary perception.",
    icon: "eye",
    accent: "cyan",
    related: ["multimodal", "robotics"],
  },
  {
    slug: "robotics",
    name: "Robotics",
    tagline: "Embodied AI and manipulation",
    description: "Bringing learned policies into the physical world: manipulation, vision-language-action models and simulation.",
    icon: "cpu",
    accent: "orange",
    related: ["computer-vision", "ai-research"],
  },
  {
    slug: "ai-product",
    name: "AI Product",
    tagline: "Designing and shipping AI products people keep using",
    description: "Product thinking for probabilistic systems: interaction patterns, latency budgets as UX, evaluation as a product function, pricing, and trust.",
    icon: "layout",
    accent: "rose",
    isFeatured: true,
    related: ["ai-engineering", "ai-industry"],
  },
  {
    slug: "ai-research",
    name: "AI Research",
    tagline: "Frontier work and how to read it",
    description: "The research frontier and the skill of reading it: landmark papers, new architectures, and the scaling results that reset the field every few months.",
    icon: "microscope",
    accent: "fuchsia",
    isFeatured: true,
    related: ["llm", "ai-fundamentals", "ai-safety"],
  },
  {
    slug: "ai-safety",
    name: "AI Safety",
    tagline: "Alignment, interpretability and misuse",
    description: "Making capable systems behave: alignment techniques, interpretability, adversarial robustness, evaluation for dangerous capabilities, and governance.",
    icon: "shield",
    accent: "slate",
    isFeatured: true,
    related: ["alignment", "ai-research", "ai-industry"],
  },
  {
    slug: "ai-infrastructure",
    name: "AI Infrastructure",
    tagline: "GPUs, kernels and distributed training",
    description: "The layer that makes training and serving possible: accelerators, CUDA and Triton kernels, distributed training strategies, and the memory hierarchy that dictates them.",
    icon: "server",
    accent: "blue",
    isFeatured: true,
    related: ["inference", "ai-engineering"],
  },
  {
    slug: "ai-tools",
    name: "AI Tools",
    tagline: "The working developer's toolbox",
    description: "Frameworks, SDKs, local runtimes, observability platforms and playgrounds worth having installed.",
    icon: "wrench",
    accent: "purple",
    related: ["ai-engineering", "ai-coding"],
  },
  {
    slug: "ai-industry",
    name: "AI Industry",
    tagline: "Labs, markets and where this is all going",
    description: "The business and policy context: lab strategies, funding, compute markets, regulation and adoption patterns.",
    icon: "trending-up",
    accent: "amber",
    related: ["ai-product", "ai-safety"],
  },

  // ── LLM subtopics ─────────────────────────────────────────────────────────
  { slug: "transformer", name: "Transformer", parent: "llm", tagline: "The architecture behind modern AI", icon: "layers", accent: "indigo", related: ["pre-training", "ai-infrastructure"] },
  { slug: "pre-training", name: "Pre-training", parent: "llm", tagline: "Building base models from raw text", icon: "layers", accent: "indigo", related: ["transformer", "moe"] },
  { slug: "fine-tuning", name: "Fine-tuning", parent: "llm", tagline: "Adapting a base model to your task", icon: "sliders", accent: "indigo", related: ["alignment", "ai-engineering"] },
  { slug: "alignment", name: "Alignment", parent: "llm", tagline: "Teaching models what we actually want", icon: "compass", accent: "indigo", related: ["rlhf", "ai-safety"] },
  { slug: "rlhf", name: "RL / RLHF", parent: "llm", tagline: "Reinforcement learning from feedback", icon: "repeat", accent: "indigo", related: ["alignment", "reasoning"] },
  { slug: "reasoning", name: "Reasoning", parent: "llm", tagline: "Test-time compute and deliberate thinking", icon: "brain", accent: "indigo", related: ["rlhf", "agents"] },
  { slug: "moe", name: "MoE", parent: "llm", tagline: "Sparse mixture-of-experts models", icon: "network", accent: "indigo", related: ["pre-training", "inference"] },
  { slug: "long-context", name: "Long Context", parent: "llm", tagline: "Making very long inputs actually work", icon: "maximize", accent: "indigo", related: ["inference", "rag"] },
  { slug: "inference", name: "Inference", parent: "llm", tagline: "Serving models fast and cheaply", icon: "zap", accent: "indigo", related: ["ai-infrastructure", "quantization"] },
  { slug: "quantization", name: "Quantization", parent: "llm", tagline: "Smaller weights, similar quality", icon: "minimize", accent: "indigo", related: ["inference"] },
  { slug: "evaluation", name: "Evaluation", parent: "llm", tagline: "Knowing whether it works", icon: "check-circle", accent: "indigo", related: ["benchmarks", "ai-engineering"] },
  { slug: "benchmarks", name: "Benchmarks", parent: "llm", tagline: "Standard tests and leaderboards", icon: "gauge", accent: "indigo", related: ["evaluation"] },
  { slug: "prompting", name: "Prompting", parent: "llm", tagline: "Getting more from a fixed model", icon: "message-square", accent: "indigo", related: ["reasoning", "ai-engineering"] },
  { slug: "llm-safety", name: "Safety", parent: "llm", tagline: "Jailbreaks, refusals and guardrails", icon: "shield", accent: "indigo", related: ["ai-safety", "alignment"] },

  // ── RAG subtopics ─────────────────────────────────────────────────────────
  { slug: "embeddings", name: "Embeddings", parent: "rag", tagline: "Turning meaning into vectors", icon: "git-branch", accent: "amber", related: ["vector-search"] },
  { slug: "vector-search", name: "Vector Search", parent: "rag", tagline: "Approximate nearest neighbours at scale", icon: "search", accent: "amber", related: ["embeddings", "ai-infrastructure"] },
  { slug: "chunking", name: "Chunking", parent: "rag", tagline: "Splitting documents without losing meaning", icon: "scissors", accent: "amber" },
  { slug: "reranking", name: "Reranking", parent: "rag", tagline: "Second-pass precision", icon: "arrow-up-down", accent: "amber", related: ["vector-search"] },
  { slug: "rag-evaluation", name: "RAG Evaluation", parent: "rag", tagline: "Measuring groundedness and recall", icon: "check-circle", accent: "amber", related: ["evaluation"] },

  // ── Agent subtopics ───────────────────────────────────────────────────────
  { slug: "tool-use", name: "Tool Use", parent: "agents", tagline: "Function calling and external actions", icon: "wrench", accent: "emerald", related: ["mcp"] },
  { slug: "agent-memory", name: "Agent Memory", parent: "agents", tagline: "State that survives the context window", icon: "archive", accent: "emerald", related: ["rag", "long-context"] },
  { slug: "multi-agent", name: "Multi-Agent", parent: "agents", tagline: "Systems of cooperating models", icon: "users", accent: "emerald" },
  { slug: "mcp", name: "MCP", parent: "agents", tagline: "Model Context Protocol integrations", icon: "plug", accent: "emerald", related: ["tool-use", "ai-tools"] },
  { slug: "agent-evaluation", name: "Agent Evaluation", parent: "agents", tagline: "Judging multi-step behaviour", icon: "check-circle", accent: "emerald", related: ["evaluation"] },

  // ── AI Engineering subtopics ──────────────────────────────────────────────
  { slug: "serving", name: "Serving", parent: "ai-engineering", tagline: "Throughput, batching and autoscaling", icon: "server", accent: "violet", related: ["inference"] },
  { slug: "observability", name: "Observability", parent: "ai-engineering", tagline: "Tracing and debugging LLM systems", icon: "activity", accent: "violet", related: ["evaluation"] },
  { slug: "cost-optimization", name: "Cost Optimization", parent: "ai-engineering", tagline: "Spending less per useful token", icon: "dollar-sign", accent: "violet", related: ["inference", "quantization"] },
  { slug: "guardrails", name: "Guardrails", parent: "ai-engineering", tagline: "Constraining output in production", icon: "shield", accent: "violet", related: ["llm-safety"] },

  // ── AI Coding subtopics ───────────────────────────────────────────────────
  { slug: "coding-agents", name: "Coding Agents", parent: "ai-coding", tagline: "Agents that write and fix code", icon: "terminal", accent: "sky", related: ["agents", "swe-benchmarks"] },
  { slug: "swe-benchmarks", name: "SWE Benchmarks", parent: "ai-coding", tagline: "Measuring real software engineering ability", icon: "gauge", accent: "sky", related: ["benchmarks"] },

  // ── Multimodal subtopics ──────────────────────────────────────────────────
  { slug: "vision-language", name: "Vision Language", parent: "multimodal", tagline: "Models that see and describe", icon: "eye", accent: "teal", related: ["computer-vision"] },
  { slug: "diffusion", name: "Diffusion", parent: "multimodal", tagline: "Generative image and video models", icon: "wand", accent: "teal" },
  { slug: "speech", name: "Speech", parent: "multimodal", tagline: "Recognition, synthesis and voice agents", icon: "mic", accent: "teal" },

  // ── Infra subtopics ───────────────────────────────────────────────────────
  { slug: "gpu-kernels", name: "GPU Kernels", parent: "ai-infrastructure", tagline: "CUDA, Triton and the memory hierarchy", icon: "cpu", accent: "blue", related: ["inference"] },
  { slug: "distributed-training", name: "Distributed Training", parent: "ai-infrastructure", tagline: "Scaling across many accelerators", icon: "network", accent: "blue", related: ["pre-training"] },
];

export const seedUsers: SeedUser[] = [
  {
    username: "sierra",
    email: "sierra@ai-atlas.dev",
    displayName: "Sierra",
    password: "atlas1234",
    role: "admin",
    headline: "Software engineer · building AI Atlas",
    bio: "Backend engineer. Curating the map so nobody else has to keep 60 browser tabs open.",
    isTrusted: true,
  },
  {
    username: "mira",
    email: "mira@ai-atlas.dev",
    displayName: "Mira Chen",
    password: "atlas1234",
    role: "editor",
    headline: "Editor · LLM & RAG",
    bio: "Ex-search infra. Reviews everything that touches retrieval.",
    isTrusted: true,
  },
  {
    username: "devan",
    email: "devan@ai-atlas.dev",
    displayName: "Devan Rao",
    password: "atlas1234",
    role: "contributor",
    headline: "AI engineer · inference nerd",
    bio: "Spends too much time reading vLLM source. Submits the good stuff.",
    isTrusted: true,
  },
  {
    username: "lena",
    email: "lena@ai-atlas.dev",
    displayName: "Lena Fischer",
    password: "atlas1234",
    role: "contributor",
    headline: "Researcher · alignment & evals",
  },
  {
    username: "kai",
    email: "kai@ai-atlas.dev",
    displayName: "Kai Watanabe",
    password: "atlas1234",
    role: "user",
    headline: "Backend engineer learning LLM inference",
  },
];
