import type { SeedResource } from "./seed-types.ts";

/** Courses, tutorials and books: the material people actually work through. */
export const learningResources: SeedResource[] = [
  {
    slug: "karpathy-neural-networks-zero-to-hero",
    title: "Neural Networks: Zero to Hero",
    url: "https://karpathy.ai/zero-to-hero.html",
    type: "course",
    topics: ["ai-fundamentals", "transformer"],
    difficulty: "intermediate",
    description:
      "Builds backpropagation, then a language model, then GPT itself, entirely from scratch in Python and PyTorch.",
    summary:
      "A video course that starts with micrograd, a scalar autograd engine written in a few dozen lines, and climbs through makemore to a working GPT implementation. Every abstraction is built before it is used, so nothing stays magic.",
    whyItMatters:
      "It is the fastest route from knowing how to program to genuinely understanding what a transformer does, and it has become the field's common reference for teaching.",
    keyTakeaways: [
      "Autograd is a small amount of code once you understand the chain rule as bookkeeping",
      "Tokenisation is a separate, messy problem from modelling and deserves its own study",
      "Attention is easier to understand as code than as notation",
      "Training instability usually traces to initialisation and normalisation choices",
    ],
    whatYouLearn: [
      "Implement backpropagation from scratch without a framework",
      "Build a character-level language model and then a transformer",
      "Diagnose training problems from loss curves and activation statistics",
      "Read PyTorch code fluently",
    ],
    prerequisites: ["Python", "Basic calculus: derivatives and the chain rule"],
    bestFor: ["Engineers", "Students", "Beginners"],
    authorName: "Andrej Karpathy",
    priceModel: "free",
    estimatedMinutes: 900,
    publishedAt: "2023-01-17",
    hasCode: true,
    isOfficial: true,
    isEditorPick: true,
    editorNote: "The best teaching in the field, free. Work through it with the code, not as background video.",
    qualityScore: 97.2,
    editorScore: 98,
    communityScore: 4.9,
    ratingsCount: 612,
    views: 78400,
    saves: 8120,
    clicks: 24600,
    completions: 4200,
    momentum: 0.62,
    metadata: { lessons: 10, certificate: false, platform: "YouTube" },
  },
  {
    slug: "stanford-cs224n",
    title: "CS224N: Natural Language Processing with Deep Learning",
    url: "https://web.stanford.edu/class/cs224n/",
    type: "course",
    topics: ["ai-fundamentals", "llm"],
    difficulty: "advanced",
    description:
      "Stanford's graduate NLP course, from word vectors through transformers and large model behaviour, with lectures and assignments public.",
    summary:
      "A full academic term covering word embeddings, recurrent models, attention, transformers, pre-training, and current topics in large language models. Assignments are substantial implementation work rather than notebook exercises.",
    whyItMatters:
      "It gives the theoretical grounding that video tutorials skip, and its problem sets are the closest thing to a standard curriculum in the field.",
    keyTakeaways: [
      "Modern NLP is a short history with a clear line from word vectors to transformers",
      "Assignment implementation is where the mathematics becomes real",
      "Evaluation methodology receives serious attention, unlike in most tutorials",
      "Lecture notes are self-contained enough to study without the video",
    ],
    whatYouLearn: [
      "Derive and implement attention and transformer components",
      "Train and evaluate models on standard NLP tasks",
      "Read NLP research papers without secondary explanations",
    ],
    prerequisites: ["Linear algebra", "Probability", "Python and PyTorch", "Calculus"],
    bestFor: ["Students", "Researchers", "ML Engineers"],
    organizationName: "Stanford University",
    priceModel: "free",
    estimatedMinutes: 2400,
    publishedAt: "2025-01-07",
    hasCode: true,
    isOfficial: true,
    qualityScore: 93.6,
    editorScore: 92,
    communityScore: 4.7,
    ratingsCount: 184,
    views: 32600,
    saves: 3280,
    clicks: 9800,
    completions: 890,
    momentum: 0.36,
    metadata: { institution: "Stanford University", lectures: 18, certificate: false },
  },
  {
    slug: "stanford-cs336-language-modeling",
    title: "CS336: Language Modeling from Scratch",
    url: "https://stanford-cs336.github.io/spring2025/",
    type: "course",
    topics: ["pre-training", "llm"],
    difficulty: "advanced",
    description:
      "Build a language model end to end: tokeniser, architecture, distributed training, alignment and inference, with no pre-built abstractions.",
    summary:
      "A course organised around five substantial assignments that require implementing the whole stack, including a BPE tokeniser, a transformer, distributed data and tensor parallel training, data curation and efficient inference. Explicitly forbids high-level libraries for the core work.",
    whyItMatters:
      "It is the only public course that teaches the systems engineering of language models rather than only the modelling, which is where most industrial work actually is.",
    keyTakeaways: [
      "Tokeniser design has measurable downstream consequences",
      "Distributed training complexity is mostly memory and communication accounting",
      "Data curation is a first-class engineering discipline, not preprocessing",
      "Inference efficiency is a design constraint on training decisions",
    ],
    whatYouLearn: [
      "Implement a BPE tokeniser and a transformer without libraries",
      "Write data and tensor parallel training code",
      "Profile and optimise training throughput on real hardware",
      "Build an efficient inference path for your own model",
    ],
    prerequisites: ["Strong Python and PyTorch", "Systems programming comfort", "Deep learning fundamentals"],
    bestFor: ["ML Engineers", "Researchers", "Students"],
    organizationName: "Stanford University",
    priceModel: "free",
    estimatedMinutes: 3600,
    publishedAt: "2025-04-01",
    hasCode: true,
    isOfficial: true,
    qualityScore: 94.8,
    editorScore: 95,
    communityScore: 4.8,
    ratingsCount: 96,
    views: 28900,
    saves: 3640,
    clicks: 8700,
    completions: 210,
    momentum: 0.88,
    metadata: { institution: "Stanford University", assignments: 5, certificate: false },
  },
  {
    slug: "fast-ai-practical-deep-learning",
    title: "Practical Deep Learning for Coders",
    url: "https://course.fast.ai/",
    type: "course",
    difficulty: "beginner",
    topics: ["ai-fundamentals"],
    description:
      "Top-down deep learning: train and deploy a working model in the first lesson, then work downwards to the theory.",
    summary:
      "Teaches by getting a state-of-the-art model working immediately and only then unpacking why it works, eventually reaching the point of implementing the pieces from scratch. Covers vision, text and tabular data, with deployment included rather than left as an exercise.",
    whyItMatters:
      "For most working programmers this is the least frustrating entry point into the field, because results come before formalism.",
    keyTakeaways: [
      "You can be productive with transfer learning long before you understand the mathematics",
      "Deployment is part of the craft and belongs in a first course",
      "Learning rate finding and one-cycle scheduling matter more than architecture choice",
      "Good defaults beat hyperparameter search for most practical problems",
    ],
    whatYouLearn: [
      "Train and fine-tune models for vision, text and tabular data",
      "Deploy a model as a working application",
      "Debug data problems that look like model problems",
    ],
    prerequisites: ["A year of programming experience, ideally Python"],
    bestFor: ["Beginners", "Engineers", "Data Scientists"],
    authorName: "Jeremy Howard",
    organizationName: "fast.ai",
    priceModel: "free",
    estimatedMinutes: 1500,
    publishedAt: "2024-04-08",
    hasCode: true,
    isOfficial: true,
    qualityScore: 91.4,
    editorScore: 90,
    communityScore: 4.7,
    ratingsCount: 342,
    views: 44200,
    saves: 4160,
    clicks: 13800,
    completions: 2600,
    momentum: 0.3,
    metadata: { lessons: 9, certificate: false, institution: "fast.ai" },
  },
  {
    slug: "mit-intro-to-deep-learning",
    title: "MIT 6.S191: Introduction to Deep Learning",
    url: "https://introtodeeplearning.com/",
    type: "course",
    topics: ["ai-fundamentals"],
    difficulty: "beginner",
    description: "MIT's intensive introductory course, refreshed each year, with lecture videos and lab notebooks.",
    summary:
      "A compact bootcamp covering neural network fundamentals, convolutional and recurrent architectures, generative models and reinforcement learning, plus guest lectures on current research. Labs are TensorFlow notebooks that run in the browser.",
    whyItMatters:
      "It is the fastest credible overview of the whole field, and being re-recorded annually means the current-topics lectures stay current.",
    keyTakeaways: [
      "The core ideas of deep learning fit into a week of focused study",
      "Labs cover music generation, computer vision and reinforcement learning",
      "Annual refresh keeps the applied sections from going stale",
      "Breadth comes at the cost of depth in any single area",
    ],
    whatYouLearn: [
      "Explain the main neural architecture families and their uses",
      "Train models in notebook labs without local setup",
      "Situate current research within the fundamentals",
    ],
    prerequisites: ["Python basics", "Introductory calculus and linear algebra"],
    bestFor: ["Beginners", "Students"],
    organizationName: "MIT",
    priceModel: "free",
    estimatedMinutes: 720,
    publishedAt: "2025-01-13",
    hasCode: true,
    isOfficial: true,
    qualityScore: 86.8,
    communityScore: 4.5,
    ratingsCount: 148,
    views: 26400,
    saves: 2140,
    clicks: 8100,
    completions: 1400,
    momentum: 0.35,
    metadata: { institution: "MIT", lectures: 10, certificate: true },
  },
  {
    slug: "hugging-face-llm-course",
    title: "Hugging Face LLM Course",
    url: "https://huggingface.co/learn/llm-course",
    type: "course",
    topics: ["llm", "ai-engineering"],
    difficulty: "beginner",
    description:
      "The practical route into the open-model ecosystem: transformers, datasets, tokenizers, fine-tuning and deployment.",
    summary:
      "A hands-on course built around the Hugging Face libraries, moving from using pipelines through the tokenizer and dataset APIs to fine-tuning and sharing your own models. Chapters on alignment and inference reflect current practice rather than the 2022 state of the art.",
    whyItMatters:
      "The open-model ecosystem runs on these libraries, and this is the maintainers' own account of how to use them properly.",
    keyTakeaways: [
      "The Trainer API removes most fine-tuning boilerplate once you know its assumptions",
      "Tokenizer behaviour explains a surprising share of confusing model outputs",
      "The datasets library handles data larger than memory without ceremony",
      "Model sharing and versioning are part of the workflow, not an afterthought",
    ],
    whatYouLearn: [
      "Fine-tune and evaluate open models with the Transformers library",
      "Build efficient data pipelines with Datasets",
      "Push models and datasets to the Hub with proper cards",
    ],
    prerequisites: ["Python", "Basic machine learning vocabulary"],
    bestFor: ["Beginners", "Engineers", "AI Engineers"],
    organizationName: "Hugging Face",
    priceModel: "free",
    estimatedMinutes: 1080,
    publishedAt: "2025-03-11",
    hasCode: true,
    isOfficial: true,
    qualityScore: 89.2,
    communityScore: 4.6,
    ratingsCount: 226,
    views: 34800,
    saves: 3020,
    clicks: 11400,
    completions: 1900,
    momentum: 0.51,
    metadata: { chapters: 12, certificate: true, platform: "Hugging Face" },
  },
  {
    slug: "hugging-face-agents-course",
    title: "Hugging Face AI Agents Course",
    url: "https://huggingface.co/learn/agents-course",
    type: "course",
    topics: ["agents", "tool-use"],
    difficulty: "intermediate",
    description:
      "Builds agents from the loop upwards: tools, memory, multi-step planning, then evaluation and deployment.",
    summary:
      "Covers agent fundamentals with smolagents and LlamaIndex, including tool definition, observation handling and multi-agent coordination, with a final project and leaderboard. Includes a unit on evaluating agents rather than only demoing them.",
    whyItMatters:
      "Most agent tutorials stop at a working demo. This one continues into evaluation, which is where agent projects usually fail.",
    keyTakeaways: [
      "The agent loop is simple; reliable tool interfaces are the hard part",
      "Memory design determines whether long tasks stay coherent",
      "Multi-agent structures add coordination cost that must earn its place",
      "Agent evaluation needs trace-level inspection, not just final answers",
    ],
    whatYouLearn: [
      "Build a tool-using agent from primitives",
      "Add memory and retrieval to a long-running agent",
      "Evaluate agent behaviour with reproducible traces",
    ],
    prerequisites: ["Python", "LLM API basics"],
    bestFor: ["AI Engineers", "Engineers"],
    organizationName: "Hugging Face",
    priceModel: "free",
    estimatedMinutes: 900,
    publishedAt: "2025-02-10",
    hasCode: true,
    isOfficial: true,
    qualityScore: 87.6,
    communityScore: 4.4,
    ratingsCount: 164,
    views: 29200,
    saves: 2760,
    clicks: 9100,
    completions: 1100,
    momentum: 0.86,
    metadata: { units: 6, certificate: true, platform: "Hugging Face" },
  },
  {
    slug: "anthropic-prompt-engineering-tutorial",
    title: "Anthropic Prompt Engineering Interactive Tutorial",
    url: "https://github.com/anthropics/prompt-eng-interactive-tutorial",
    type: "tutorial",
    topics: ["prompting"],
    difficulty: "beginner",
    description:
      "Nine chapters of runnable exercises that build prompting skill from basic structure to complex multi-part instructions.",
    summary:
      "A notebook-based curriculum that teaches prompt structure, role assignment, output formatting, step-by-step reasoning and prompt chaining, each with exercises graded against expected behaviour. Includes an appendix on tool use and search.",
    whyItMatters:
      "Prompting advice is mostly folklore online. This is a structured, testable version of it from the people who train the model.",
    keyTakeaways: [
      "Clear structure and explicit output format beat clever phrasing",
      "Being direct about the task removes most ambiguity failures",
      "Examples work best when they demonstrate edge cases, not the easy path",
      "Chaining separate prompts often beats one complicated prompt",
    ],
    whatYouLearn: [
      "Write prompts with reliable, parseable output",
      "Debug a failing prompt systematically rather than by trial and error",
      "Decide when to chain prompts instead of extending one",
    ],
    prerequisites: [],
    bestFor: ["Beginners", "Product Managers", "Engineers"],
    organizationName: "Anthropic",
    priceModel: "free",
    estimatedMinutes: 240,
    publishedAt: "2024-08-20",
    hasCode: true,
    isOfficial: true,
    qualityScore: 88.4,
    editorScore: 89,
    communityScore: 4.7,
    ratingsCount: 208,
    views: 31600,
    saves: 3480,
    clicks: 10200,
    completions: 2100,
    momentum: 0.57,
    metadata: { chapters: 9, stars: 15600, language: "Jupyter Notebook" },
  },
  {
    slug: "full-stack-llm-bootcamp",
    title: "Full Stack LLM Bootcamp",
    url: "https://fullstackdeeplearning.com/llm-bootcamp/",
    type: "course",
    topics: ["ai-engineering"],
    difficulty: "intermediate",
    description:
      "A recorded bootcamp on shipping LLM applications: prompting, retrieval, UX, evaluation and deployment.",
    summary:
      "Lectures from practitioners covering prompt engineering, retrieval augmentation, LLM operations, user experience for probabilistic systems, and launching a product. Written for engineers who need to ship rather than publish.",
    whyItMatters:
      "It was the first serious curriculum for LLM application engineering as a discipline distinct from machine learning research.",
    keyTakeaways: [
      "UX design for non-deterministic output is a first-order product problem",
      "Evaluation infrastructure should exist before the first prompt is tuned",
      "Retrieval quality dominates perceived model quality in most applications",
      "Operational concerns like cost and latency shape architecture from day one",
    ],
    whatYouLearn: [
      "Structure an LLM application project end to end",
      "Design interfaces that degrade gracefully when the model is wrong",
      "Set up evaluation before scaling a prototype",
    ],
    prerequisites: ["Software engineering experience", "Basic LLM API familiarity"],
    bestFor: ["Engineers", "AI Engineers", "Founders"],
    organizationName: "Full Stack Deep Learning",
    priceModel: "free",
    estimatedMinutes: 660,
    publishedAt: "2024-05-15",
    hasCode: true,
    qualityScore: 84.6,
    communityScore: 4.3,
    ratingsCount: 118,
    views: 21800,
    saves: 1840,
    clicks: 6900,
    completions: 720,
    momentum: 0.32,
    metadata: { lectures: 10, certificate: false },
  },
  {
    slug: "deeplearning-ai-prompt-engineering",
    title: "ChatGPT Prompt Engineering for Developers",
    url: "https://www.deeplearning.ai/short-courses/chatgpt-prompt-engineering-for-developers/",
    type: "course",
    topics: ["prompting", "ai-engineering"],
    difficulty: "beginner",
    description:
      "A short, code-first introduction to prompting patterns for developers, taught with runnable notebooks.",
    summary:
      "Covers summarising, inferring, transforming and expanding text, plus iterative prompt development and a simple chatbot, in about ninety minutes of notebook work. Deliberately narrow and practical.",
    whyItMatters:
      "It is the shortest path from never having called an LLM API to using one competently in code.",
    keyTakeaways: [
      "Iterative refinement is the actual workflow, not one-shot prompt writing",
      "Delimiters and explicit output schemas prevent most parsing problems",
      "Asking the model to check its own conditions catches many silent failures",
      "Temperature is a product decision as much as a technical one",
    ],
    whatYouLearn: [
      "Call an LLM API and shape its output reliably",
      "Apply the core prompting patterns for text tasks",
      "Build a minimal chatbot with managed conversation state",
    ],
    prerequisites: ["Basic Python"],
    bestFor: ["Beginners", "Engineers", "Product Managers"],
    authorName: "Isa Fulford and Andrew Ng",
    organizationName: "DeepLearning.AI",
    priceModel: "free",
    estimatedMinutes: 90,
    publishedAt: "2024-02-06",
    hasCode: true,
    isOfficial: true,
    qualityScore: 82.8,
    communityScore: 4.4,
    ratingsCount: 296,
    views: 38400,
    saves: 2680,
    clicks: 12100,
    completions: 3400,
    momentum: 0.28,
    metadata: { lessons: 9, certificate: false, platform: "DeepLearning.AI" },
  },
  {
    slug: "ai-engineering-book",
    title: "AI Engineering: Building Applications with Foundation Models",
    url: "https://www.oreilly.com/library/view/ai-engineering/9781098166298/",
    type: "book",
    topics: ["ai-engineering", "evaluation"],
    difficulty: "intermediate",
    description:
      "The reference text for building products on foundation models: evaluation, adaptation, RAG, agents, inference and cost.",
    summary:
      "Covers the full application stack in the order a real project encounters it, beginning with evaluation because it determines everything downstream, then prompt engineering, retrieval, fine-tuning, agents, inference optimisation and architecture. Notably candid about what does not work.",
    whyItMatters:
      "It is the closest thing the discipline has to a textbook, and it is unusually honest about trade-offs that vendor material glosses over.",
    keyTakeaways: [
      "Evaluation is the foundation of the stack, not the final step",
      "Choose prompting, retrieval or fine-tuning by constraint, not by fashion",
      "Inference cost and latency belong in the architecture discussion from the start",
      "Most production failures are data and evaluation failures, not model failures",
    ],
    whatYouLearn: [
      "Design an evaluation suite before building the product",
      "Choose deliberately between prompting, RAG and fine-tuning",
      "Plan inference cost, latency and caching as architecture",
      "Structure an AI application team's workflow",
    ],
    prerequisites: ["Software engineering experience"],
    bestFor: ["AI Engineers", "Engineers", "Product Managers", "Founders"],
    authorName: "Chip Huyen",
    organizationName: "O'Reilly",
    priceModel: "paid",
    estimatedMinutes: 1560,
    publishedAt: "2025-01-14",
    isEditorPick: true,
    editorNote: "The book to hand a strong backend engineer who has been asked to ship an AI feature next quarter.",
    qualityScore: 94.4,
    editorScore: 96,
    communityScore: 4.8,
    ratingsCount: 214,
    views: 36200,
    saves: 4480,
    clicks: 11200,
    completions: 640,
    momentum: 0.81,
    metadata: { isbn: "978-1098166298", pages: 534, publisher: "O'Reilly" },
  },
  {
    slug: "hands-on-large-language-models",
    title: "Hands-On Large Language Models",
    url: "https://www.oreilly.com/library/view/hands-on-large-language/9781098150956/",
    type: "book",
    topics: ["llm", "embeddings"],
    difficulty: "beginner",
    description:
      "A heavily illustrated, code-first tour of language models: tokens, embeddings, retrieval, fine-tuning and generation.",
    summary:
      "Uses nearly three hundred custom diagrams alongside runnable notebooks to explain how language models represent and generate text, covering embeddings, semantic search, classification, clustering and fine-tuning with open models.",
    whyItMatters:
      "The visual explanations do work that prose cannot, particularly for embeddings and attention, and every chapter runs as code.",
    keyTakeaways: [
      "Embeddings are the workhorse of most practical applications, not generation",
      "Diagrams make attention and tokenisation concrete in a way equations do not",
      "Open models are enough for nearly every exercise in the book",
      "Semantic search and clustering are underrated first projects",
    ],
    whatYouLearn: [
      "Use embeddings for search, classification and clustering",
      "Fine-tune small open models on your own data",
      "Explain tokenisation and attention with confidence",
    ],
    prerequisites: ["Basic Python"],
    bestFor: ["Beginners", "Engineers", "Data Scientists"],
    authorName: "Jay Alammar and Maarten Grootendorst",
    organizationName: "O'Reilly",
    priceModel: "paid",
    estimatedMinutes: 1200,
    publishedAt: "2024-09-24",
    hasCode: true,
    qualityScore: 90.6,
    editorScore: 91,
    communityScore: 4.8,
    ratingsCount: 168,
    views: 27400,
    saves: 3120,
    clicks: 8600,
    completions: 480,
    momentum: 0.56,
    metadata: { isbn: "978-1098150956", pages: 428, publisher: "O'Reilly" },
  },
  {
    slug: "deep-learning-book",
    title: "Deep Learning",
    url: "https://www.deeplearningbook.org/",
    type: "book",
    topics: ["ai-fundamentals"],
    difficulty: "advanced",
    description:
      "The Goodfellow, Bengio and Courville textbook: the mathematical foundations of deep learning, free to read online.",
    summary:
      "Three parts covering the required mathematics, established deep learning practice, and research topics including representation learning and generative models. Predates transformers but remains the standard reference for the underlying theory.",
    whyItMatters:
      "When you need to know why an optimiser or regulariser behaves the way it does, this is where the answer actually is.",
    keyTakeaways: [
      "The mathematics review in part one is a complete prerequisite course",
      "Optimisation and regularisation are treated with real rigour",
      "The generative modelling chapters predate diffusion and transformers",
      "It is a reference to consult repeatedly, not a book to read once",
    ],
    whatYouLearn: [
      "Work through the probability and linear algebra deep learning requires",
      "Explain optimisation behaviour from theory rather than folklore",
      "Read theoretical machine learning papers on their own terms",
    ],
    prerequisites: ["Undergraduate mathematics", "Programming experience"],
    bestFor: ["Researchers", "Students"],
    authorName: "Ian Goodfellow, Yoshua Bengio and Aaron Courville",
    organizationName: "MIT Press",
    priceModel: "free",
    estimatedMinutes: 3000,
    publishedAt: "2016-11-18",
    isOfficial: true,
    qualityScore: 92.4,
    communityScore: 4.5,
    ratingsCount: 262,
    views: 29600,
    saves: 3860,
    clicks: 8400,
    completions: 180,
    momentum: 0.14,
    metadata: { pages: 800, publisher: "MIT Press", isbn: "978-0262035613" },
  },
  {
    slug: "speech-and-language-processing",
    title: "Speech and Language Processing",
    url: "https://web.stanford.edu/~jurafsky/slp3/",
    type: "book",
    topics: ["ai-fundamentals", "llm"],
    difficulty: "intermediate",
    description:
      "Jurafsky and Martin's standard NLP textbook, with draft chapters covering transformers and large language models kept current online.",
    summary:
      "Spans classical NLP through modern neural methods: regular expressions and edit distance, n-gram models, embeddings, transformers, pre-training, fine-tuning, machine translation, dialogue and speech. Chapters are released as free drafts and revised regularly.",
    whyItMatters:
      "It provides the linguistic and historical grounding that makes current model behaviour comprehensible rather than mysterious.",
    keyTakeaways: [
      "Classical methods still explain many failure modes of neural systems",
      "Each chapter is self-contained enough to use as a reference",
      "Evaluation methodology is treated as a subject in its own right",
      "Draft chapters keep pace with current model developments",
    ],
    whatYouLearn: [
      "Ground modern NLP in its linguistic foundations",
      "Explain machine translation, dialogue and speech pipelines",
      "Choose appropriate evaluation metrics for language tasks",
    ],
    prerequisites: ["Basic probability", "Programming experience"],
    bestFor: ["Students", "Engineers", "Researchers"],
    authorName: "Jurafsky & Martin",
    organizationName: "Stanford University",
    priceModel: "free",
    estimatedMinutes: 2400,
    publishedAt: "2025-01-12",
    isOfficial: true,
    qualityScore: 91.2,
    communityScore: 4.6,
    ratingsCount: 144,
    views: 22800,
    saves: 2540,
    clicks: 6800,
    completions: 210,
    momentum: 0.27,
    metadata: { pages: 640, edition: "3rd draft" },
  },
  {
    slug: "karpathy-deep-dive-into-llms",
    title: "Deep Dive into LLMs like ChatGPT",
    url: "https://www.youtube.com/watch?v=7xTGNNLPyMI",
    type: "video",
    topics: ["llm", "pre-training"],
    difficulty: "intermediate",
    description:
      "A three-hour explanation of the entire LLM lifecycle, from pre-training data to post-training and reasoning, for a general technical audience.",
    summary:
      "Walks through tokenisation, pre-training on internet text, what the base model actually is, supervised fine-tuning, reinforcement learning, hallucination, tool use and the current state of reasoning models. Assumes no mathematics but does not simplify away substance.",
    whyItMatters:
      "It is the best single explanation of what these systems are and are not, and it is the right thing to send a colleague who asks how ChatGPT works.",
    keyTakeaways: [
      "A base model is a text simulator; the assistant persona comes entirely from post-training",
      "Hallucination is a predictable consequence of the training objective",
      "Reasoning models trade inference compute for accuracy on hard problems",
      "Model quality claims are best evaluated against how each stage of training works",
    ],
    whatYouLearn: [
      "Explain pre-training, SFT and RL stages to a non-specialist",
      "Predict where a model will fail and why",
      "Read model release announcements critically",
    ],
    prerequisites: [],
    bestFor: ["Engineers", "Product Managers", "Beginners"],
    authorName: "Andrej Karpathy",
    priceModel: "free",
    estimatedMinutes: 212,
    publishedAt: "2025-02-05",
    isOfficial: true,
    isEditorPick: true,
    editorNote: "Send this to anyone who needs to understand LLMs in one sitting. No mathematics, no hand-waving.",
    qualityScore: 95.2,
    editorScore: 96,
    communityScore: 4.9,
    ratingsCount: 428,
    views: 58200,
    saves: 5640,
    clicks: 18400,
    momentum: 0.9,
    metadata: { platform: "YouTube", durationSeconds: 12720 },
  },
  {
    slug: "karpathy-lets-build-gpt",
    title: "Let's Build GPT: From Scratch, in Code",
    url: "https://www.youtube.com/watch?v=kCc8FmEb1nY",
    type: "video",
    topics: ["transformer", "pre-training"],
    difficulty: "intermediate",
    description: "Types out a working GPT line by line, explaining each component as it appears.",
    summary:
      "Builds a character-level transformer from an empty file: bigram baseline, then self-attention, multi-head attention, feed-forward blocks, residual connections and layer normalisation, ending with a small trained model generating text.",
    whyItMatters:
      "Watching the architecture assembled incrementally makes the transformer paper legible in a way no diagram achieves.",
    keyTakeaways: [
      "Attention is a weighted aggregation whose weights are learned from the data itself",
      "Residual connections and layer normalisation are what make depth trainable",
      "The bigram baseline clarifies exactly what attention adds",
      "A complete GPT is a few hundred lines of readable code",
    ],
    whatYouLearn: [
      "Implement a transformer from scratch in PyTorch",
      "Explain each architectural component's purpose",
      "Train a small language model on your own text",
    ],
    prerequisites: ["Python", "Basic PyTorch"],
    bestFor: ["Engineers", "Students"],
    authorName: "Andrej Karpathy",
    priceModel: "free",
    estimatedMinutes: 117,
    publishedAt: "2023-01-17",
    hasCode: true,
    isOfficial: true,
    qualityScore: 94.6,
    editorScore: 95,
    communityScore: 4.9,
    ratingsCount: 386,
    views: 52400,
    saves: 5180,
    clicks: 16800,
    momentum: 0.44,
    metadata: { platform: "YouTube", durationSeconds: 7020 },
  },
  {
    slug: "3blue1brown-transformers-explained",
    title: "But What Is a GPT? Visual Intro to Transformers",
    url: "https://www.youtube.com/watch?v=wjZofJX0v4M",
    type: "video",
    topics: ["transformer", "ai-fundamentals"],
    difficulty: "beginner",
    description:
      "An animated explanation of what happens to a token as it passes through a transformer, with no code required.",
    summary:
      "Uses 3Blue1Brown's animation style to show embeddings as directions in high-dimensional space, then how attention moves information between them and how the final layer produces a distribution over next tokens.",
    whyItMatters:
      "It builds the geometric intuition that makes the mathematics feel inevitable rather than arbitrary, and it is accessible to people who will never write training code.",
    keyTakeaways: [
      "Embeddings are directions in space and semantic relationships are geometric",
      "Attention moves context between token representations",
      "The unembedding step turns a vector back into a distribution over vocabulary",
      "Softmax temperature has a visual, intuitive meaning",
    ],
    whatYouLearn: [
      "Picture what a transformer does to a sequence",
      "Explain embeddings and attention without notation",
      "Follow more technical explanations afterwards",
    ],
    prerequisites: [],
    bestFor: ["Beginners", "Product Managers", "Students"],
    authorName: "Grant Sanderson",
    organizationName: "3Blue1Brown",
    priceModel: "free",
    estimatedMinutes: 27,
    publishedAt: "2024-04-01",
    isOfficial: true,
    qualityScore: 93.2,
    editorScore: 94,
    communityScore: 4.9,
    ratingsCount: 342,
    views: 46800,
    saves: 4020,
    clicks: 14600,
    momentum: 0.49,
    metadata: { platform: "YouTube", durationSeconds: 1620 },
  },
];
