import type { SeedResource } from "./seed-types.ts";

/** Research: the papers a practitioner is expected to have read, or at least know. */
export const paperResources: SeedResource[] = [
  {
    slug: "attention-is-all-you-need",
    title: "Attention Is All You Need",
    url: "https://arxiv.org/abs/1706.03762",
    type: "paper",
    topics: ["transformer", "llm", "ai-research"],
    difficulty: "advanced",
    description:
      "The paper that introduced the Transformer, replacing recurrence and convolution with self-attention alone.",
    summary:
      "Introduces an encoder-decoder architecture built entirely from multi-head self-attention and position-wise feed-forward layers. Because there is no recurrence, every position is computed in parallel, which is what made scaling to today's model sizes practical. Includes the scaled dot-product attention formulation, sinusoidal positional encodings and the original WMT translation results.",
    whyItMatters:
      "Every large language model in production descends from this architecture. Reading it is the difference between using attention and understanding why it works.",
    keyTakeaways: [
      "Self-attention replaces recurrence entirely, making training parallelisable across sequence positions",
      "Multi-head attention lets the model attend to different representation subspaces at once",
      "Scaling the dot product by the square root of the key dimension keeps gradients stable",
      "Positional encodings inject order into an otherwise permutation-invariant operation",
    ],
    whatYouLearn: [
      "Derive scaled dot-product and multi-head attention from first principles",
      "Explain why Transformers parallelise where RNNs cannot",
      "Read the architecture diagrams that later papers assume you know",
    ],
    prerequisites: ["Linear algebra: matrix multiplication and softmax", "Basic sequence-to-sequence modelling"],
    bestFor: ["Researchers", "Engineers", "Students"],
    authorName: "Ashish Vaswani et al.",
    organizationName: "Google Brain",
    priceModel: "free",
    estimatedMinutes: 45,
    publishedAt: "2017-06-12",
    isOfficial: true,
    isEditorPick: true,
    editorNote: "The single highest-leverage paper in modern AI. If you read one thing on this list, read this.",
    qualityScore: 98.4,
    editorScore: 99,
    communityScore: 4.9,
    ratingsCount: 842,
    views: 94200,
    saves: 8930,
    clicks: 28400,
    momentum: 0.28,
    metadata: { arxivId: "1706.03762", citations: 173000, venue: "NeurIPS 2017" },
  },
  {
    slug: "scaling-laws-for-neural-language-models",
    title: "Scaling Laws for Neural Language Models",
    url: "https://arxiv.org/abs/2001.08361",
    type: "paper",
    topics: ["pre-training", "ai-research"],
    difficulty: "advanced",
    description:
      "Empirical power laws relating language model loss to parameters, dataset size and compute across seven orders of magnitude.",
    summary:
      "Shows that cross-entropy loss falls as a predictable power law in model size, dataset size and training compute, with architecture details mattering far less than scale. Establishes that larger models are more sample-efficient and derives how to allocate a fixed compute budget between size and steps.",
    whyItMatters:
      "This is the paper that turned model training from craft into forecasting, and it is the intellectual justification for the entire era of frontier-scale pre-training.",
    keyTakeaways: [
      "Loss follows smooth power laws in compute, parameters and data over many orders of magnitude",
      "Architecture width and depth matter much less than total parameter count",
      "Larger models reach a given loss with fewer tokens seen, so they are more sample-efficient",
      "Optimal compute allocation favours making the model bigger over training it longer",
    ],
    whatYouLearn: [
      "Predict the loss of a training run before you launch it",
      "Reason about compute budgets in terms of parameters against tokens",
      "Read later scaling work, including Chinchilla, in context",
    ],
    prerequisites: ["Language model training basics", "Comfort reading log-log plots"],
    bestFor: ["Researchers", "ML Engineers"],
    authorName: "Jared Kaplan et al.",
    organizationName: "OpenAI",
    priceModel: "free",
    estimatedMinutes: 50,
    publishedAt: "2020-01-23",
    isOfficial: true,
    qualityScore: 93.1,
    editorScore: 92,
    communityScore: 4.6,
    ratingsCount: 214,
    views: 31400,
    saves: 2870,
    clicks: 8900,
    momentum: 0.31,
    metadata: { arxivId: "2001.08361", citations: 6400 },
  },
  {
    slug: "chinchilla-compute-optimal-training",
    title: "Training Compute-Optimal Large Language Models",
    url: "https://arxiv.org/abs/2203.15556",
    type: "paper",
    topics: ["pre-training", "ai-research"],
    difficulty: "advanced",
    description:
      "The Chinchilla paper: for a fixed compute budget, models should be far smaller and trained on far more tokens than was standard.",
    summary:
      "Trains over 400 models to fit the relationship between parameters, tokens and loss, and finds that model size and training tokens should scale roughly in equal proportion. Chinchilla, at 70B parameters trained on 1.4T tokens, outperforms the 280B Gopher on the same compute.",
    whyItMatters:
      "It corrected the field's bias toward parameter count and set the token-heavy training recipe that Llama and nearly every open model since has followed.",
    keyTakeaways: [
      "Parameters and training tokens should scale roughly one-to-one for a fixed compute budget",
      "Most large models of the era were substantially under-trained for their size",
      "A smaller, well-trained model is cheaper to serve at equal or better quality",
      "Data quantity and quality became the binding constraint on frontier training",
    ],
    whatYouLearn: [
      "Apply the Chinchilla ratio when sizing a training run",
      "Explain why serving cost, not just training cost, argues for smaller models",
      "Interpret the compute-optimal frontier and its assumptions",
    ],
    prerequisites: ["Scaling laws for neural language models"],
    bestFor: ["Researchers", "ML Engineers"],
    authorName: "Jordan Hoffmann et al.",
    organizationName: "Google DeepMind",
    priceModel: "free",
    estimatedMinutes: 45,
    publishedAt: "2022-03-29",
    isOfficial: true,
    qualityScore: 92.6,
    communityScore: 4.5,
    ratingsCount: 168,
    views: 24800,
    saves: 2210,
    clicks: 7100,
    momentum: 0.34,
    metadata: { arxivId: "2203.15556", citations: 3900 },
  },
  {
    slug: "instructgpt-training-with-human-feedback",
    title: "Training Language Models to Follow Instructions with Human Feedback",
    url: "https://arxiv.org/abs/2203.02155",
    type: "paper",
    topics: ["rlhf", "alignment"],
    difficulty: "advanced",
    description:
      "The InstructGPT paper: supervised fine-tuning plus a learned reward model and PPO turns a raw language model into an assistant.",
    summary:
      "Describes the three-stage recipe behind instruction-following models: collect demonstrations for supervised fine-tuning, collect human preference comparisons to train a reward model, then optimise the policy against that reward with PPO. A 1.3B InstructGPT is preferred to the 175B base GPT-3 by human raters.",
    whyItMatters:
      "This is the origin of the assistant behaviour everyone now takes for granted, and the reference point for every alignment technique that followed.",
    keyTakeaways: [
      "Human preference data, not more pre-training, is what produces instruction following",
      "A 100x smaller aligned model can beat a larger unaligned one on human preference",
      "The reward model is a learned proxy and can be over-optimised, so KL penalties matter",
      "Alignment introduces a measurable tax on some benchmark capabilities",
    ],
    whatYouLearn: [
      "Explain the SFT, reward model and PPO pipeline end to end",
      "Identify where preference data quality determines model behaviour",
      "Reason about reward over-optimisation and its mitigations",
    ],
    prerequisites: ["Language model fine-tuning", "Basic reinforcement learning vocabulary"],
    bestFor: ["Researchers", "ML Engineers", "AI Engineers"],
    authorName: "Long Ouyang et al.",
    organizationName: "OpenAI",
    priceModel: "free",
    estimatedMinutes: 55,
    publishedAt: "2022-03-04",
    isOfficial: true,
    qualityScore: 94.2,
    editorScore: 93,
    communityScore: 4.7,
    ratingsCount: 246,
    views: 38600,
    saves: 3540,
    clicks: 11200,
    momentum: 0.42,
    metadata: { arxivId: "2203.02155", citations: 11800 },
  },
  {
    slug: "direct-preference-optimization",
    title: "Direct Preference Optimization",
    url: "https://arxiv.org/abs/2305.18290",
    type: "paper",
    topics: ["alignment", "rlhf"],
    difficulty: "advanced",
    description:
      "Shows that preference alignment can be done with a simple classification loss, no reward model and no reinforcement learning loop.",
    summary:
      "Derives that the RLHF objective has a closed-form optimal policy, which allows the preference problem to be reparameterised as a direct loss on the policy itself. DPO matches or beats PPO-based RLHF on summarisation and dialogue while being dramatically simpler and more stable to train.",
    whyItMatters:
      "DPO made alignment accessible to teams without an RL infrastructure, and it is now the default starting point for open-model preference tuning.",
    keyTakeaways: [
      "The RLHF optimum can be expressed directly, removing the need for an explicit reward model",
      "Training reduces to a binary cross-entropy loss over preferred and rejected pairs",
      "Fewer moving parts means far fewer failure modes than PPO in practice",
      "The KL constraint to the reference policy is implicit in the loss",
    ],
    whatYouLearn: [
      "Implement preference tuning with a standard training loop",
      "Compare DPO against PPO-based RLHF on cost and stability",
      "Prepare and clean a paired preference dataset",
    ],
    prerequisites: ["InstructGPT and the RLHF pipeline", "Fine-tuning with PyTorch"],
    bestFor: ["ML Engineers", "Researchers"],
    authorName: "Rafael Rafailov et al.",
    organizationName: "Stanford University",
    priceModel: "free",
    estimatedMinutes: 45,
    publishedAt: "2023-05-29",
    isOfficial: true,
    qualityScore: 91.8,
    communityScore: 4.6,
    ratingsCount: 132,
    views: 21300,
    saves: 2140,
    clicks: 6400,
    momentum: 0.58,
    metadata: { arxivId: "2305.18290", citations: 3100, venue: "NeurIPS 2023" },
  },
  {
    slug: "constitutional-ai",
    title: "Constitutional AI: Harmlessness from AI Feedback",
    url: "https://arxiv.org/abs/2212.08073",
    type: "paper",
    topics: ["alignment", "ai-safety"],
    difficulty: "advanced",
    description:
      "Replaces human harmlessness labels with model self-critique against an explicit written set of principles.",
    summary:
      "Introduces a two-phase method: the model critiques and revises its own responses against a constitution, producing supervised data, then preference labels for harmlessness are generated by the model rather than by humans. The result is a less evasive assistant whose values are written down and auditable.",
    whyItMatters:
      "It reframed alignment from an opaque labelling process into an explicit, reviewable specification, and it is the backbone of Claude's training.",
    keyTakeaways: [
      "Harmlessness preferences can be generated by a model given written principles",
      "Self-critique and revision produces training data without human red-teamers in the loop",
      "Writing values down makes them auditable and contestable",
      "Reduces the evasiveness that pure human harmlessness training tends to produce",
    ],
    whatYouLearn: [
      "Design a principle set that a model can actually apply",
      "Build a self-critique and revision data pipeline",
      "Weigh AI feedback against human feedback for safety training",
    ],
    prerequisites: ["RLHF fundamentals"],
    bestFor: ["Researchers", "AI Engineers"],
    authorName: "Yuntao Bai et al.",
    organizationName: "Anthropic",
    priceModel: "free",
    estimatedMinutes: 60,
    publishedAt: "2022-12-15",
    isOfficial: true,
    qualityScore: 90.4,
    editorScore: 91,
    communityScore: 4.4,
    ratingsCount: 96,
    views: 17600,
    saves: 1580,
    clicks: 5200,
    momentum: 0.46,
    metadata: { arxivId: "2212.08073", citations: 2400 },
  },
  {
    slug: "chain-of-thought-prompting",
    title: "Chain-of-Thought Prompting Elicits Reasoning in LLMs",
    url: "https://arxiv.org/abs/2201.11903",
    type: "paper",
    topics: ["reasoning", "prompting"],
    difficulty: "intermediate",
    description:
      "Showing a model worked examples with intermediate steps unlocks multi-step reasoning that direct prompting misses.",
    summary:
      "Demonstrates that prompting with exemplars containing intermediate reasoning steps substantially improves arithmetic, commonsense and symbolic reasoning, and that the effect only emerges at sufficient model scale. Includes the GSM8K results that made the technique famous.",
    whyItMatters:
      "It established that a large part of reasoning ability is latent and unlocked by prompting, which set off the entire line of work leading to today's reasoning models.",
    keyTakeaways: [
      "Intermediate steps in the prompt let the model allocate more computation to the problem",
      "The gain is an emergent property of scale and is absent in small models",
      "Errors become inspectable because the intermediate steps are visible",
      "Works without any fine-tuning or gradient updates",
    ],
    whatYouLearn: [
      "Write few-shot prompts that surface intermediate reasoning",
      "Recognise which task families benefit and which do not",
      "Evaluate reasoning traces rather than only final answers",
    ],
    prerequisites: [],
    bestFor: ["AI Engineers", "Practitioners", "Product Managers"],
    authorName: "Jason Wei et al.",
    organizationName: "Google Brain",
    priceModel: "free",
    estimatedMinutes: 35,
    publishedAt: "2022-01-28",
    isOfficial: true,
    qualityScore: 92.9,
    communityScore: 4.7,
    ratingsCount: 288,
    views: 42100,
    saves: 4180,
    clicks: 13600,
    momentum: 0.52,
    metadata: { arxivId: "2201.11903", citations: 12600, venue: "NeurIPS 2022" },
  },
  {
    slug: "self-consistency-improves-reasoning",
    title: "Self-Consistency Improves Chain of Thought Reasoning",
    url: "https://arxiv.org/abs/2203.11171",
    type: "paper",
    topics: ["reasoning", "prompting"],
    difficulty: "intermediate",
    description:
      "Sample several reasoning paths at a non-zero temperature and take the majority answer instead of trusting one greedy decode.",
    summary:
      "Replaces greedy decoding with sampling a diverse set of reasoning paths and marginalising over them by majority vote on the final answer. Gains are large on arithmetic and commonsense benchmarks, at the cost of running inference several times.",
    whyItMatters:
      "It was the first widely adopted demonstration that spending more inference compute buys accuracy, which is the idea underpinning today's reasoning-time scaling.",
    keyTakeaways: [
      "Diverse sampled reasoning paths often converge on the correct answer even when individual paths err",
      "Majority voting over final answers is a strong and trivially simple aggregator",
      "Accuracy can be bought with inference compute rather than more training",
      "Costs scale linearly with the number of samples, so it needs a budget policy",
    ],
    whatYouLearn: [
      "Implement self-consistency sampling and aggregation",
      "Trade accuracy against inference cost deliberately",
      "Detect tasks where majority voting fails to help",
    ],
    prerequisites: ["Chain-of-thought prompting"],
    bestFor: ["AI Engineers", "Practitioners"],
    authorName: "Xuezhi Wang et al.",
    organizationName: "Google Brain",
    priceModel: "free",
    estimatedMinutes: 30,
    publishedAt: "2022-03-21",
    isOfficial: true,
    qualityScore: 85.7,
    communityScore: 4.3,
    ratingsCount: 74,
    views: 14200,
    saves: 1120,
    clicks: 4100,
    momentum: 0.44,
    metadata: { arxivId: "2203.11171", citations: 3600, venue: "ICLR 2023" },
  },
  {
    slug: "deepseek-r1-reasoning-via-rl",
    title: "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via RL",
    url: "https://arxiv.org/abs/2501.12948",
    type: "paper",
    topics: ["reasoning", "rlhf", "llm"],
    difficulty: "advanced",
    description:
      "Reinforcement learning with verifiable rewards produces long-form reasoning behaviour, with open weights and a published recipe.",
    summary:
      "Shows that pure RL against automatically checkable rewards causes a base model to develop extended reasoning, self-verification and backtracking without supervised reasoning traces. Covers R1-Zero's emergent behaviour, the cold-start data used to fix readability, and distillation into smaller dense models.",
    whyItMatters:
      "It made frontier-grade reasoning reproducible outside the largest labs and reset expectations for what open models can do.",
    keyTakeaways: [
      "Verifiable rewards let RL improve reasoning without human reasoning traces",
      "Longer chains of thought emerge on their own as training proceeds",
      "A small cold-start SFT set fixes the readability problems of pure RL",
      "Reasoning distils effectively into much smaller dense models",
    ],
    whatYouLearn: [
      "Explain reinforcement learning with verifiable rewards",
      "Identify which tasks admit automatic reward checking",
      "Understand how reasoning models differ from instruction-tuned ones at inference",
    ],
    prerequisites: ["RLHF fundamentals", "Chain-of-thought prompting"],
    bestFor: ["Researchers", "ML Engineers", "AI Engineers"],
    authorName: "DeepSeek-AI",
    organizationName: "DeepSeek",
    priceModel: "free",
    estimatedMinutes: 55,
    publishedAt: "2025-01-22",
    isOfficial: true,
    isEditorPick: true,
    editorNote: "The clearest published account of how reasoning models are actually trained, from a team that shipped the weights.",
    qualityScore: 95.6,
    editorScore: 96,
    communityScore: 4.8,
    ratingsCount: 318,
    views: 61400,
    saves: 6820,
    clicks: 19800,
    momentum: 0.94,
    metadata: { arxivId: "2501.12948", citations: 1900 },
  },
  {
    slug: "llama-3-herd-of-models",
    title: "The Llama 3 Herd of Models",
    url: "https://arxiv.org/abs/2407.21783",
    type: "paper",
    topics: ["llm", "pre-training"],
    difficulty: "advanced",
    description:
      "A 90-page engineering account of pre-training, post-training and infrastructure for a frontier-class open model family.",
    summary:
      "Documents the full production pipeline for Llama 3: data curation and filtering, the 405B dense architecture choice, scaling and hardware failure handling at 16k GPUs, then post-training with SFT, rejection sampling and DPO. Also covers long-context extension, tool use and safety evaluations.",
    whyItMatters:
      "It is the most complete public description of how a frontier model is actually built, including the unglamorous infrastructure detail that papers usually omit.",
    keyTakeaways: [
      "Data curation and deduplication do more for quality than architectural novelty",
      "Hardware failures at 16k GPU scale are routine and must be designed for",
      "A dense 405B model was chosen over MoE for training stability and simplicity",
      "Post-training is several rounds of SFT, rejection sampling and DPO, not one pass",
    ],
    whatYouLearn: [
      "Trace a frontier training pipeline from raw data to released weights",
      "Understand practical trade-offs between dense and sparse architectures",
      "See how long-context and tool use are added after pre-training",
    ],
    prerequisites: ["Transformer architecture", "Scaling laws"],
    bestFor: ["ML Engineers", "Researchers"],
    authorName: "Llama Team",
    organizationName: "Meta AI",
    priceModel: "free",
    estimatedMinutes: 120,
    publishedAt: "2024-07-31",
    isOfficial: true,
    qualityScore: 93.8,
    editorScore: 94,
    communityScore: 4.7,
    ratingsCount: 176,
    views: 34900,
    saves: 3410,
    clicks: 10400,
    momentum: 0.55,
    metadata: { arxivId: "2407.21783", citations: 2800, pages: 92 },
  },
  {
    slug: "mixtral-of-experts",
    title: "Mixtral of Experts",
    url: "https://arxiv.org/abs/2401.04088",
    type: "paper",
    topics: ["moe", "llm"],
    difficulty: "advanced",
    description:
      "A sparse mixture-of-experts model that uses 13B active parameters out of 47B total and matches far larger dense models.",
    summary:
      "Describes Mixtral 8x7B, where a router selects two of eight feed-forward experts per token per layer. The result gives the quality of a much larger model at the inference cost of a small one, and the paper reports routing behaviour analysis alongside benchmark results.",
    whyItMatters:
      "It brought sparse MoE from research into practical open-weight deployment and reframed how teams think about the cost of capability.",
    keyTakeaways: [
      "Only two of eight experts are active per token, decoupling capacity from inference cost",
      "Total memory footprint stays large even though compute per token is small",
      "Routing is learned and shows little of the topical specialisation people expect",
      "Serving MoE efficiently requires expert-aware batching and placement",
    ],
    whatYouLearn: [
      "Explain sparse MoE routing and its cost model",
      "Distinguish active from total parameters when sizing hardware",
      "Judge when MoE is the wrong choice for your serving constraints",
    ],
    prerequisites: ["Transformer architecture"],
    bestFor: ["ML Engineers", "Researchers"],
    authorName: "Albert Q. Jiang et al.",
    organizationName: "Mistral AI",
    priceModel: "free",
    estimatedMinutes: 35,
    publishedAt: "2024-01-08",
    isOfficial: true,
    qualityScore: 87.9,
    communityScore: 4.4,
    ratingsCount: 88,
    views: 18700,
    saves: 1490,
    clicks: 5600,
    momentum: 0.48,
    metadata: { arxivId: "2401.04088", citations: 1600 },
  },
  {
    slug: "lora-low-rank-adaptation",
    title: "LoRA: Low-Rank Adaptation of Large Language Models",
    url: "https://arxiv.org/abs/2106.09685",
    type: "paper",
    topics: ["fine-tuning"],
    difficulty: "intermediate",
    description:
      "Freezes the base weights and trains small low-rank update matrices, cutting trainable parameters by orders of magnitude.",
    summary:
      "Proposes learning a low-rank decomposition of the weight update instead of updating the full matrix, based on the observation that adaptation has low intrinsic rank. Trainable parameters drop by up to 10,000x with no additional inference latency once the update is merged.",
    whyItMatters:
      "LoRA is why fine-tuning a capable model no longer requires a GPU cluster, and it is the foundation of the entire adapter ecosystem.",
    keyTakeaways: [
      "Weight updates during adaptation have low intrinsic rank and compress well",
      "Base weights stay frozen, so one model can serve many task adapters",
      "Merging the adapter at inference adds zero latency",
      "Rank and target modules are the two knobs that actually matter",
    ],
    whatYouLearn: [
      "Choose rank, alpha and target modules for a task",
      "Serve many adapters against one base model",
      "Explain why LoRA is cheap in memory as well as compute",
    ],
    prerequisites: ["Fine-tuning basics", "Linear algebra: matrix rank"],
    bestFor: ["ML Engineers", "AI Engineers", "Practitioners"],
    authorName: "Edward J. Hu et al.",
    organizationName: "Microsoft",
    priceModel: "free",
    estimatedMinutes: 40,
    publishedAt: "2021-06-17",
    isOfficial: true,
    hasCode: true,
    qualityScore: 93.4,
    editorScore: 92,
    communityScore: 4.8,
    ratingsCount: 264,
    views: 40800,
    saves: 4320,
    clicks: 12900,
    momentum: 0.4,
    metadata: { arxivId: "2106.09685", citations: 9700, venue: "ICLR 2022" },
  },
  {
    slug: "qlora-efficient-finetuning",
    title: "QLoRA: Efficient Finetuning of Quantized LLMs",
    url: "https://arxiv.org/abs/2305.14314",
    type: "paper",
    topics: ["fine-tuning", "quantization"],
    difficulty: "advanced",
    description:
      "Fine-tunes a 4-bit quantised base model with LoRA adapters, fitting a 65B model onto a single 48GB GPU.",
    summary:
      "Combines a new 4-bit NormalFloat data type, double quantisation and paged optimisers so that back-propagation through a quantised base model preserves full 16-bit fine-tuning quality. Includes the Guanaco models trained on a single GPU.",
    whyItMatters:
      "It collapsed the hardware requirement for serious fine-tuning from a cluster to one card, which is the reason a hobbyist can now tune a large model.",
    keyTakeaways: [
      "4-bit NormalFloat is information-theoretically suited to normally distributed weights",
      "Double quantisation compresses the quantisation constants themselves",
      "Paged optimisers absorb the memory spikes that would otherwise cause out-of-memory failures",
      "Quality matches 16-bit full fine-tuning on the benchmarks tested",
    ],
    whatYouLearn: [
      "Fine-tune a large model within a single-GPU memory budget",
      "Reason about quantisation error where it actually matters",
      "Configure paged optimisers and gradient checkpointing together",
    ],
    prerequisites: ["LoRA", "GPU memory fundamentals"],
    bestFor: ["ML Engineers", "Practitioners"],
    authorName: "Tim Dettmers et al.",
    organizationName: "University of Washington",
    priceModel: "free",
    estimatedMinutes: 45,
    publishedAt: "2023-05-23",
    isOfficial: true,
    hasCode: true,
    qualityScore: 90.2,
    communityScore: 4.6,
    ratingsCount: 142,
    views: 23600,
    saves: 2380,
    clicks: 7300,
    momentum: 0.5,
    metadata: { arxivId: "2305.14314", citations: 4200, venue: "NeurIPS 2023" },
  },
  {
    slug: "retrieval-augmented-generation-paper",
    title: "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
    url: "https://arxiv.org/abs/2005.11401",
    type: "paper",
    topics: ["rag", "embeddings"],
    difficulty: "intermediate",
    description: "The paper that named RAG: a dense retriever and a generator trained together over a non-parametric memory.",
    summary:
      "Couples a dense passage retriever over a Wikipedia index with a seq2seq generator, so knowledge lives in a swappable index rather than only in the weights. Compares per-sequence and per-token marginalisation and shows gains on open-domain question answering.",
    whyItMatters:
      "Every production RAG system is a descendant of this design, and the paper's framing of parametric against non-parametric memory is still the right way to think about it.",
    keyTakeaways: [
      "Knowledge in an index can be updated without retraining the generator",
      "Retriever and generator can be trained jointly rather than bolted together",
      "Retrieved evidence gives generations something to be attributed to",
      "Retrieval quality caps end-to-end quality, so the retriever is the leverage point",
    ],
    whatYouLearn: [
      "Explain the retriever and generator split and where each fails",
      "See why index freshness beats retraining for factual knowledge",
      "Read modern RAG papers with the original terminology",
    ],
    prerequisites: ["Transformer basics", "Vector similarity search"],
    bestFor: ["AI Engineers", "Engineers", "Researchers"],
    authorName: "Patrick Lewis et al.",
    organizationName: "Meta AI",
    priceModel: "free",
    estimatedMinutes: 40,
    publishedAt: "2020-05-22",
    isOfficial: true,
    qualityScore: 91.6,
    editorScore: 90,
    communityScore: 4.5,
    ratingsCount: 198,
    views: 33200,
    saves: 3260,
    clicks: 10100,
    momentum: 0.47,
    metadata: { arxivId: "2005.11401", citations: 7800, venue: "NeurIPS 2020" },
  },
  {
    slug: "lost-in-the-middle",
    title: "Lost in the Middle: How Language Models Use Long Contexts",
    url: "https://arxiv.org/abs/2307.03172",
    type: "paper",
    topics: ["long-context", "rag"],
    difficulty: "intermediate",
    description:
      "Models attend well to the start and end of a long context and reliably miss what sits in the middle.",
    summary:
      "Measures retrieval accuracy as a function of where the relevant document sits in the context window and finds a pronounced U-shaped curve. Performance can degrade below that of a much shorter context, and the effect persists in models explicitly trained for long context.",
    whyItMatters:
      "It is the empirical reason that stuffing everything into a huge context window is not a substitute for good retrieval and reranking.",
    keyTakeaways: [
      "Accuracy follows a U-shape against the position of the relevant passage",
      "More context can make answers worse, not better",
      "Reranking so the best evidence sits at the edges measurably helps",
      "Long-context training reduces but does not remove the effect",
    ],
    whatYouLearn: [
      "Order retrieved context deliberately rather than arbitrarily",
      "Design position-aware evaluations for your own retrieval stack",
      "Argue concretely against the replace-RAG-with-long-context claim",
    ],
    prerequisites: ["Basic RAG architecture"],
    bestFor: ["AI Engineers", "Engineers"],
    authorName: "Nelson F. Liu et al.",
    organizationName: "Stanford University",
    priceModel: "free",
    estimatedMinutes: 30,
    publishedAt: "2023-07-06",
    isOfficial: true,
    qualityScore: 88.3,
    communityScore: 4.5,
    ratingsCount: 116,
    views: 19400,
    saves: 1920,
    clicks: 6100,
    momentum: 0.53,
    metadata: { arxivId: "2307.03172", citations: 2300, venue: "TACL 2024" },
  },
  {
    slug: "flashattention",
    title: "FlashAttention: Fast and Memory-Efficient Exact Attention",
    url: "https://arxiv.org/abs/2205.14135",
    type: "paper",
    topics: ["gpu-kernels", "inference"],
    difficulty: "advanced",
    description:
      "An IO-aware attention kernel that never materialises the full attention matrix, making attention faster and linear in memory.",
    summary:
      "Reframes attention as a memory-bandwidth problem rather than a FLOP problem, then tiles the computation in SRAM and recomputes intermediates in the backward pass. The result is exact attention with large wall-clock speedups and memory that scales linearly in sequence length.",
    whyItMatters:
      "Long context became affordable because of this kernel, and it is the canonical example of why hardware-aware implementation beats asymptotic cleverness.",
    keyTakeaways: [
      "Attention is bound by HBM bandwidth, not arithmetic throughput",
      "Tiling into SRAM with online softmax avoids materialising the N by N matrix",
      "Recomputation in the backward pass trades cheap FLOPs for expensive memory traffic",
      "The output is numerically exact, not an approximation",
    ],
    whatYouLearn: [
      "Reason about the GPU memory hierarchy when optimising kernels",
      "Explain online softmax and why it enables tiling",
      "Distinguish exact optimisation from approximate attention methods",
    ],
    prerequisites: ["Attention mechanism", "GPU architecture basics", "CUDA concepts"],
    bestFor: ["ML Engineers", "Researchers"],
    authorName: "Tri Dao et al.",
    organizationName: "Stanford University",
    priceModel: "free",
    estimatedMinutes: 50,
    publishedAt: "2022-05-27",
    isOfficial: true,
    hasCode: true,
    qualityScore: 92.1,
    editorScore: 93,
    communityScore: 4.7,
    ratingsCount: 124,
    views: 22400,
    saves: 2160,
    clicks: 6800,
    momentum: 0.38,
    metadata: { arxivId: "2205.14135", citations: 3400, venue: "NeurIPS 2022" },
  },
  {
    slug: "vllm-paged-attention",
    title: "Efficient Memory Management for LLM Serving with PagedAttention",
    url: "https://arxiv.org/abs/2309.06180",
    type: "paper",
    topics: ["serving", "inference"],
    difficulty: "advanced",
    description:
      "Applies operating-system paging to the KV cache, eliminating the fragmentation that wastes most serving memory.",
    summary:
      "Identifies internal and external fragmentation in contiguous KV cache allocation as the dominant waste in LLM serving, then manages the cache in fixed-size blocks with a page table. Sharing blocks across sequences enables cheap parallel sampling and beam search, delivering large throughput gains.",
    whyItMatters:
      "This is the paper behind vLLM, and its ideas are now in essentially every serious inference server.",
    keyTakeaways: [
      "Contiguous KV cache allocation wastes the majority of reserved memory",
      "Block-based paging with a page table nearly eliminates fragmentation",
      "Copy-on-write block sharing makes parallel sampling almost free",
      "Higher memory efficiency converts directly into larger batches and throughput",
    ],
    whatYouLearn: [
      "Explain KV cache memory behaviour under real traffic",
      "Reason about throughput against latency in continuous batching",
      "Read inference server documentation with the right mental model",
    ],
    prerequisites: ["Transformer inference and KV caching", "Operating system paging"],
    bestFor: ["ML Engineers", "Engineers"],
    authorName: "Woosuk Kwon et al.",
    organizationName: "UC Berkeley",
    priceModel: "free",
    estimatedMinutes: 45,
    publishedAt: "2023-09-12",
    isOfficial: true,
    hasCode: true,
    qualityScore: 90.7,
    communityScore: 4.6,
    ratingsCount: 92,
    views: 17200,
    saves: 1640,
    clicks: 5300,
    momentum: 0.61,
    metadata: { arxivId: "2309.06180", citations: 1800, venue: "SOSP 2023" },
  },
  {
    slug: "react-synergizing-reasoning-and-acting",
    title: "ReAct: Synergizing Reasoning and Acting in Language Models",
    url: "https://arxiv.org/abs/2210.03629",
    type: "paper",
    topics: ["agents", "tool-use", "reasoning"],
    difficulty: "intermediate",
    description:
      "Interleaves reasoning traces with tool calls so the model can plan, act, observe and revise in one loop.",
    summary:
      "Proposes alternating thought, action and observation steps, letting the model use external tools to ground its reasoning while using reasoning to decide which tool to call. Reduces hallucination relative to chain-of-thought alone and outperforms action-only agents on interactive benchmarks.",
    whyItMatters:
      "Practically every agent framework in use today implements some version of this loop, usually without citing it.",
    keyTakeaways: [
      "Reasoning and acting reinforce each other when interleaved in one trace",
      "External observations ground the reasoning and cut hallucination",
      "The trace is human-readable, which makes agent failures debuggable",
      "Loop control and stopping criteria are where real implementations get hard",
    ],
    whatYouLearn: [
      "Implement a thought-action-observation agent loop",
      "Design tool interfaces a model can actually use reliably",
      "Debug an agent by reading its trace rather than guessing",
    ],
    prerequisites: ["Chain-of-thought prompting", "Function calling basics"],
    bestFor: ["AI Engineers", "Engineers", "Practitioners"],
    authorName: "Shunyu Yao et al.",
    organizationName: "Princeton University",
    priceModel: "free",
    estimatedMinutes: 40,
    publishedAt: "2022-10-06",
    isOfficial: true,
    isEditorPick: true,
    editorNote: "The origin of the agent loop everyone reimplements. Read it before adopting a framework that hides it from you.",
    qualityScore: 91.2,
    editorScore: 94,
    communityScore: 4.6,
    ratingsCount: 186,
    views: 29800,
    saves: 3140,
    clicks: 9400,
    momentum: 0.74,
    metadata: { arxivId: "2210.03629", citations: 5200, venue: "ICLR 2023" },
  },
  {
    slug: "toolformer",
    title: "Toolformer: Language Models Can Teach Themselves to Use Tools",
    url: "https://arxiv.org/abs/2302.04761",
    type: "paper",
    topics: ["tool-use", "agents"],
    difficulty: "advanced",
    description:
      "A model annotates its own training data with API calls, keeping only the calls that reduce its loss.",
    summary:
      "Uses self-supervision to decide where tool calls help: the model proposes candidate API calls in text, executes them, and keeps only those that lower perplexity on the following tokens. The resulting model calls calculators, search and translation without any human tool-use annotations.",
    whyItMatters:
      "It showed tool use could be learned rather than prompted, and its filtering criterion is a genuinely elegant piece of self-supervision design.",
    keyTakeaways: [
      "Tool calls can be filtered by whether they reduce loss on subsequent tokens",
      "No human annotation of tool usage is required",
      "Learned tool use generalises better than prompt-specified tool use",
      "The approach is limited to tools whose outputs are short and text-like",
    ],
    whatYouLearn: [
      "Design a self-supervised filter for synthetic training data",
      "Compare learned against prompted tool invocation",
      "Recognise which tools fit this training scheme",
    ],
    prerequisites: ["Language model fine-tuning", "Perplexity as an objective"],
    bestFor: ["Researchers", "ML Engineers"],
    authorName: "Timo Schick et al.",
    organizationName: "Meta AI",
    priceModel: "free",
    estimatedMinutes: 35,
    publishedAt: "2023-02-09",
    isOfficial: true,
    qualityScore: 82.4,
    communityScore: 4.1,
    ratingsCount: 48,
    views: 9100,
    saves: 620,
    clicks: 2700,
    momentum: 0.29,
    metadata: { arxivId: "2302.04761", citations: 1500, venue: "NeurIPS 2023" },
  },
  {
    slug: "swe-bench",
    title: "SWE-bench: Can Language Models Resolve Real-World GitHub Issues?",
    url: "https://arxiv.org/abs/2310.06770",
    type: "paper",
    topics: ["swe-benchmarks", "benchmarks", "coding-agents"],
    difficulty: "intermediate",
    description:
      "A benchmark of real GitHub issues and their real test suites, where a solution counts only if the tests pass.",
    summary:
      "Collects task instances from popular Python repositories, each pairing an issue with the pull request that fixed it and the tests that verify it. Success requires editing an unfamiliar multi-file codebase so the hidden tests pass, which early models solved at low single-digit rates.",
    whyItMatters:
      "It is the benchmark that coding agents are now measured by, and it exposed how far short of real software work function-level benchmarks fell.",
    keyTakeaways: [
      "Evaluation is execution-based, so a passing solution cannot be faked",
      "Tasks span multiple files and require navigating an unfamiliar repository",
      "Retrieval of the right files is often the hard part, not the edit",
      "Contamination and environment setup are the benchmark's main weaknesses",
    ],
    whatYouLearn: [
      "Read coding-agent leaderboards critically",
      "Design execution-based evaluations for your own agents",
      "Separate retrieval failures from editing failures in agent traces",
    ],
    prerequisites: ["Python", "Git and pull request workflow"],
    bestFor: ["Engineers", "AI Engineers", "Researchers"],
    authorName: "Carlos E. Jimenez et al.",
    organizationName: "Princeton University",
    priceModel: "free",
    estimatedMinutes: 40,
    publishedAt: "2023-10-10",
    isOfficial: true,
    hasCode: true,
    qualityScore: 89.6,
    editorScore: 90,
    communityScore: 4.5,
    ratingsCount: 104,
    views: 20600,
    saves: 2040,
    clicks: 6500,
    momentum: 0.83,
    metadata: { arxivId: "2310.06770", citations: 1400, venue: "ICLR 2024" },
  },
  {
    slug: "clip-transferable-visual-models",
    title: "Learning Transferable Visual Models From Natural Language Supervision",
    url: "https://arxiv.org/abs/2103.00020",
    type: "paper",
    topics: ["vision-language", "multimodal"],
    difficulty: "advanced",
    description:
      "CLIP: contrastive training on 400 million image and caption pairs yields a model that classifies without task-specific labels.",
    summary:
      "Trains an image encoder and a text encoder to align matching pairs in a shared embedding space, then performs zero-shot classification by comparing an image against text prompts for each class. Matches supervised ImageNet baselines without seeing a single ImageNet label.",
    whyItMatters:
      "CLIP embeddings underpin text-to-image generation, multimodal retrieval and most vision-language models that followed.",
    keyTakeaways: [
      "Natural language captions are a scalable supervision signal for vision",
      "A shared embedding space enables zero-shot classification through prompts",
      "Prompt wording measurably changes accuracy, so prompt engineering applies to vision too",
      "Web-scale training data brings web-scale biases with it",
    ],
    whatYouLearn: [
      "Explain contrastive image-text pre-training",
      "Use CLIP embeddings for retrieval and zero-shot classification",
      "Anticipate the failure modes of caption-supervised models",
    ],
    prerequisites: ["Deep learning fundamentals", "Contrastive learning"],
    bestFor: ["Researchers", "ML Engineers"],
    authorName: "Alec Radford et al.",
    organizationName: "OpenAI",
    priceModel: "free",
    estimatedMinutes: 55,
    publishedAt: "2021-02-26",
    isOfficial: true,
    qualityScore: 91.4,
    communityScore: 4.6,
    ratingsCount: 138,
    views: 24100,
    saves: 2280,
    clicks: 7200,
    momentum: 0.26,
    metadata: { arxivId: "2103.00020", citations: 27000, venue: "ICML 2021" },
  },
  {
    slug: "latent-diffusion-models",
    title: "High-Resolution Image Synthesis with Latent Diffusion Models",
    url: "https://arxiv.org/abs/2112.10752",
    type: "paper",
    topics: ["diffusion", "computer-vision"],
    difficulty: "advanced",
    description:
      "Runs diffusion in a compressed latent space instead of pixel space, which is what made Stable Diffusion feasible.",
    summary:
      "Trains an autoencoder to compress images into a perceptually equivalent latent space, then runs the diffusion process there, cutting compute by orders of magnitude. Adds cross-attention conditioning so text, layout and other signals can steer generation.",
    whyItMatters:
      "This is the architecture behind Stable Diffusion and the reason high-quality image generation runs on consumer hardware.",
    keyTakeaways: [
      "Perceptual compression removes imperceptible detail before diffusion begins",
      "Diffusion in latent space is dramatically cheaper than in pixel space",
      "Cross-attention provides a general conditioning interface for any modality",
      "The autoencoder's reconstruction quality bounds the final output quality",
    ],
    whatYouLearn: [
      "Explain the two-stage latent diffusion pipeline",
      "Identify where conditioning enters the denoising process",
      "Reason about the compute and quality trade-off of latent compression",
    ],
    prerequisites: ["Diffusion model basics", "Autoencoders", "Attention mechanism"],
    bestFor: ["Researchers", "ML Engineers"],
    authorName: "Robin Rombach et al.",
    organizationName: "LMU Munich",
    priceModel: "free",
    estimatedMinutes: 50,
    publishedAt: "2021-12-20",
    isOfficial: true,
    hasCode: true,
    qualityScore: 89.8,
    communityScore: 4.5,
    ratingsCount: 96,
    views: 18300,
    saves: 1560,
    clicks: 5400,
    momentum: 0.24,
    metadata: { arxivId: "2112.10752", citations: 14000, venue: "CVPR 2022" },
  },
  {
    slug: "whisper-robust-speech-recognition",
    title: "Robust Speech Recognition via Large-Scale Weak Supervision",
    url: "https://arxiv.org/abs/2212.04356",
    type: "paper",
    topics: ["speech", "multimodal"],
    difficulty: "intermediate",
    description:
      "Whisper: 680,000 hours of weakly supervised multilingual audio produce a model that generalises without fine-tuning.",
    summary:
      "Trains a single encoder-decoder on a large, noisy, multilingual and multitask audio corpus covering transcription, translation and language identification. Zero-shot robustness across accents and domains approaches human reliability without any dataset-specific tuning.",
    whyItMatters:
      "It made high-quality open speech recognition a solved problem for most practical purposes, and the weights are permissively licensed.",
    keyTakeaways: [
      "Scale and diversity of weakly labelled data beat clean but narrow datasets",
      "One model handles transcription, translation and language ID through task tokens",
      "Zero-shot robustness matters more than in-domain benchmark accuracy",
      "Long-form audio needs a chunking and stitching strategy at inference",
    ],
    whatYouLearn: [
      "Deploy speech recognition without collecting training data",
      "Understand weak supervision as a scaling strategy",
      "Handle long-form audio transcription in practice",
    ],
    prerequisites: ["Sequence-to-sequence models"],
    bestFor: ["Engineers", "ML Engineers", "Practitioners"],
    authorName: "Alec Radford et al.",
    organizationName: "OpenAI",
    priceModel: "free",
    estimatedMinutes: 40,
    publishedAt: "2022-12-06",
    isOfficial: true,
    hasCode: true,
    qualityScore: 88.1,
    communityScore: 4.6,
    ratingsCount: 82,
    views: 15900,
    saves: 1380,
    clicks: 4800,
    momentum: 0.33,
    metadata: { arxivId: "2212.04356", citations: 4600, venue: "ICML 2023" },
  },
  {
    slug: "mmlu-benchmark",
    title: "MMLU: Measuring Massive Multitask Language Understanding",
    url: "https://arxiv.org/abs/2009.03300",
    type: "benchmark",
    topics: ["benchmarks", "evaluation"],
    difficulty: "intermediate",
    description:
      "Fifty-seven subjects of multiple-choice exam questions, from elementary mathematics to professional law.",
    summary:
      "Assembles exam-style questions across humanities, social sciences, STEM and professional domains to measure breadth of knowledge in a zero-shot or few-shot setting. Became the default headline number for model comparisons for several years.",
    whyItMatters:
      "Understanding MMLU, including its label noise and contamination problems, is necessary to read any model announcement critically.",
    keyTakeaways: [
      "Breadth across 57 subjects makes narrow overfitting harder but not impossible",
      "Multiple-choice format is cheap to grade and easy to game",
      "Known label errors put a ceiling on meaningful scores",
      "Training-set contamination inflates reported results over time",
    ],
    whatYouLearn: [
      "Interpret MMLU numbers with appropriate scepticism",
      "Explain contamination and why it degrades benchmark value",
      "Choose task-specific evaluations over general leaderboards",
    ],
    prerequisites: [],
    bestFor: ["Product Managers", "Engineers", "Researchers"],
    authorName: "Dan Hendrycks et al.",
    organizationName: "UC Berkeley",
    priceModel: "free",
    estimatedMinutes: 30,
    publishedAt: "2020-09-07",
    isOfficial: true,
    qualityScore: 84.2,
    communityScore: 4.1,
    ratingsCount: 58,
    views: 12400,
    saves: 840,
    clicks: 3600,
    momentum: 0.22,
    metadata: { arxivId: "2009.03300", citations: 5100, venue: "ICLR 2021" },
  },
];
