import type { SeedResource } from "./seed-types.ts";

/** Code, docs, writing and products: what you reach for while actually building. */
export const buildingResources: SeedResource[] = [
  {
    slug: "langchain",
    title: "LangChain",
    url: "https://github.com/langchain-ai/langchain",
    type: "github",
    topics: ["ai-engineering", "rag", "agents"],
    difficulty: "intermediate",
    description:
      "The most widely used framework for composing LLM applications, with integrations for nearly every model, store and tool.",
    summary:
      "Provides abstractions for chaining model calls, retrieval, memory and tools, plus LangGraph for stateful agent workflows. Its breadth of integrations is unmatched, which is both the main reason to adopt it and the main source of complaints about its layering.",
    whyItMatters:
      "Whether or not you adopt it, its abstractions have shaped how the industry talks about LLM applications, and its integration list is a map of the ecosystem.",
    keyTakeaways: [
      "Integration breadth is the real value; the abstractions are replaceable",
      "LangGraph handles stateful, cyclic workflows that simple chains cannot",
      "Debugging through several abstraction layers is the recurring complaint",
      "Reading the source of one chain teaches the pattern faster than the docs",
    ],
    whatYouLearn: [
      "Compose retrieval, memory and tool use into an application",
      "Model an agent workflow as an explicit state graph",
      "Judge when a framework is helping and when to drop to the SDK",
    ],
    prerequisites: ["Python or TypeScript", "LLM API basics"],
    bestFor: ["Engineers", "AI Engineers"],
    organizationName: "LangChain",
    priceModel: "free",
    estimatedMinutes: 90,
    publishedAt: "2025-06-18",
    isOfficial: true,
    hasCode: true,
    qualityScore: 87.2,
    editorScore: 84,
    communityScore: 4.1,
    ratingsCount: 486,
    views: 68400,
    saves: 5920,
    clicks: 22100,
    momentum: 0.58,
    metadata: { stars: 112000, language: "Python", license: "MIT" },
  },
  {
    slug: "llamaindex",
    title: "LlamaIndex",
    url: "https://github.com/run-llama/llama_index",
    type: "github",
    topics: ["rag", "vector-search"],
    difficulty: "intermediate",
    description:
      "A data framework focused on retrieval: ingestion, chunking, indexing and query engines over your own documents.",
    summary:
      "Specialises in the data side of RAG, with connectors for many document sources, several index structures, and query engines that support routing, sub-question decomposition and response synthesis. Also provides agent workflows built on those retrieval primitives.",
    whyItMatters:
      "If retrieval quality is your bottleneck, its index and query abstractions are more directly useful than a general-purpose chain framework.",
    keyTakeaways: [
      "Chunking and metadata design determine retrieval quality more than the model does",
      "Query decomposition handles multi-part questions that single retrieval cannot",
      "Different index structures suit different query patterns",
      "Ingestion pipelines need versioning as much as application code does",
    ],
    whatYouLearn: [
      "Build a document ingestion and indexing pipeline",
      "Configure query engines for routing and decomposition",
      "Evaluate and iterate on retrieval quality",
    ],
    prerequisites: ["Python", "Embedding and vector search basics"],
    bestFor: ["Engineers", "AI Engineers", "Data Scientists"],
    organizationName: "LlamaIndex",
    priceModel: "freemium",
    estimatedMinutes: 75,
    publishedAt: "2025-05-22",
    isOfficial: true,
    hasCode: true,
    qualityScore: 85.8,
    communityScore: 4.2,
    ratingsCount: 264,
    views: 42600,
    saves: 3480,
    clicks: 13400,
    momentum: 0.52,
    metadata: { stars: 39000, language: "Python", license: "MIT" },
  },
  {
    slug: "huggingface-transformers",
    title: "Transformers",
    url: "https://github.com/huggingface/transformers",
    type: "github",
    topics: ["llm", "ai-engineering"],
    difficulty: "intermediate",
    description:
      "The library that made pre-trained models interchangeable, with a shared API across thousands of architectures.",
    summary:
      "Provides model definitions, tokenisers, training utilities and pipelines for a very large catalogue of architectures across text, vision and audio, with weights hosted on the Hub. The deliberately repetitive single-file model layout makes any individual model easy to read and modify.",
    whyItMatters:
      "It is the substrate of open machine learning: nearly every open model ships a Transformers implementation on release day.",
    keyTakeaways: [
      "One API across thousands of models makes swapping architectures cheap",
      "Single-file model definitions favour readability over abstraction",
      "The tokeniser and config objects are where most integration bugs live",
      "Pipelines are the fastest route from weights to a working demo",
    ],
    whatYouLearn: [
      "Load, run and fine-tune open models",
      "Read a model implementation to understand its architecture",
      "Use the Hub for weights, datasets and evaluation",
    ],
    prerequisites: ["Python", "PyTorch basics"],
    bestFor: ["ML Engineers", "Engineers", "Researchers"],
    organizationName: "Hugging Face",
    priceModel: "free",
    estimatedMinutes: 60,
    publishedAt: "2025-07-02",
    isOfficial: true,
    hasCode: true,
    isEditorPick: true,
    editorNote: "The default toolbox for open models. Learn its tokeniser and config objects and the rest follows.",
    qualityScore: 95.8,
    editorScore: 96,
    communityScore: 4.8,
    ratingsCount: 524,
    views: 71200,
    saves: 6840,
    clicks: 23400,
    momentum: 0.47,
    metadata: { stars: 143000, language: "Python", license: "Apache-2.0" },
  },
  {
    slug: "nanogpt",
    title: "nanoGPT",
    url: "https://github.com/karpathy/nanoGPT",
    type: "github",
    topics: ["transformer", "pre-training"],
    difficulty: "advanced",
    description:
      "The simplest repository that still reproduces GPT-2: about three hundred lines of model code and three hundred of training loop.",
    summary:
      "A deliberately minimal training codebase that prioritises readability while remaining fast enough to reproduce GPT-2 scale results on real hardware. Includes distributed training, mixed precision and a Shakespeare demo that trains in minutes.",
    whyItMatters:
      "It is the reference implementation people actually read, and it is small enough to modify confidently for experiments.",
    keyTakeaways: [
      "A complete, competitive GPT training stack fits in a few hundred lines",
      "Mixed precision and compilation account for most of the achievable speedup",
      "Data loading is memory-mapped tokens, not a complicated pipeline",
      "The small Shakespeare configuration makes experimentation cheap",
    ],
    whatYouLearn: [
      "Read and modify a complete transformer training loop",
      "Run distributed training with torchrun",
      "Reproduce GPT-2 scale results and interpret the loss curve",
    ],
    prerequisites: ["PyTorch", "Transformer architecture", "GPU access for larger runs"],
    bestFor: ["ML Engineers", "Students", "Researchers"],
    authorName: "Andrej Karpathy",
    priceModel: "free",
    estimatedMinutes: 120,
    publishedAt: "2024-06-14",
    isOfficial: true,
    hasCode: true,
    qualityScore: 92.8,
    editorScore: 93,
    communityScore: 4.8,
    ratingsCount: 218,
    views: 38200,
    saves: 4260,
    clicks: 12400,
    momentum: 0.39,
    metadata: { stars: 42000, language: "Python", license: "MIT" },
  },
  {
    slug: "vllm",
    title: "vLLM",
    url: "https://github.com/vllm-project/vllm",
    type: "github",
    topics: ["serving", "inference"],
    difficulty: "advanced",
    description:
      "High-throughput inference server built on PagedAttention and continuous batching, with an OpenAI-compatible API.",
    summary:
      "Serves open models with paged KV cache management, continuous batching, prefix caching, tensor parallelism and quantisation support. The OpenAI-compatible endpoint means existing clients work unchanged.",
    whyItMatters:
      "It is the default answer for self-hosted inference at scale, and it turned a research result into infrastructure people run in production.",
    keyTakeaways: [
      "Continuous batching keeps the GPU busy instead of waiting for slow requests",
      "Prefix caching pays off substantially with shared system prompts",
      "Throughput and latency are traded explicitly through batching configuration",
      "Quantisation choices interact with throughput in non-obvious ways",
    ],
    whatYouLearn: [
      "Deploy an open model behind a production inference server",
      "Tune batching, caching and parallelism for your traffic shape",
      "Measure tokens per second and cost per million tokens honestly",
    ],
    prerequisites: ["Linux and CUDA basics", "Transformer inference concepts"],
    bestFor: ["ML Engineers", "Engineers"],
    priceModel: "free",
    estimatedMinutes: 80,
    publishedAt: "2025-07-10",
    isOfficial: true,
    hasCode: true,
    qualityScore: 91.6,
    editorScore: 92,
    communityScore: 4.7,
    ratingsCount: 186,
    views: 34400,
    saves: 3260,
    clicks: 11200,
    momentum: 0.71,
    metadata: { stars: 48000, language: "Python", license: "Apache-2.0" },
  },
  {
    slug: "ollama",
    title: "Ollama",
    url: "https://github.com/ollama/ollama",
    type: "github",
    topics: ["inference", "ai-tools"],
    difficulty: "beginner",
    description: "Run open models locally with one command, on macOS, Linux or Windows.",
    summary:
      "Packages model weights, quantisation and a local HTTP server behind a single-command experience, with an OpenAI-compatible endpoint and a model library covering the popular open families. Handles GPU detection and memory management without configuration.",
    whyItMatters:
      "It removed the setup barrier for local inference, which makes private, zero-cost experimentation the default rather than a project.",
    keyTakeaways: [
      "Quantised models make useful local inference possible on a laptop",
      "The local API is OpenAI-compatible, so application code ports directly",
      "Modelfiles let you version prompts and parameters alongside the model",
      "Memory, not compute, is the binding constraint on consumer hardware",
    ],
    whatYouLearn: [
      "Run and serve open models locally",
      "Choose a quantisation level for your hardware",
      "Develop against a local endpoint before paying for an API",
    ],
    prerequisites: [],
    bestFor: ["Beginners", "Engineers", "Practitioners"],
    priceModel: "free",
    estimatedMinutes: 25,
    publishedAt: "2025-06-30",
    isOfficial: true,
    hasCode: true,
    qualityScore: 89.4,
    communityScore: 4.7,
    ratingsCount: 398,
    views: 56800,
    saves: 5140,
    clicks: 19600,
    momentum: 0.64,
    metadata: { stars: 152000, language: "Go", license: "MIT" },
  },
  {
    slug: "dspy",
    title: "DSPy",
    url: "https://github.com/stanfordnlp/dspy",
    type: "github",
    topics: ["prompting", "ai-engineering"],
    difficulty: "advanced",
    description:
      "Programs language models with declarative modules and compiles the prompts automatically against a metric.",
    summary:
      "Replaces hand-written prompt strings with typed signatures and composable modules, then uses optimisers to search for few-shot examples and instructions that maximise a metric you define. Reframes prompt engineering as compilation.",
    whyItMatters:
      "It is the most serious attempt to make prompting an engineering discipline with a compiler and an objective rather than a craft.",
    keyTakeaways: [
      "Declaring input and output signatures separates intent from prompt wording",
      "Optimisers search the prompt space against a metric you must define first",
      "Requires a real evaluation set, which is the discipline it forces on you",
      "Swapping the underlying model triggers recompilation rather than a rewrite",
    ],
    whatYouLearn: [
      "Express an LLM pipeline as composable typed modules",
      "Define metrics that an optimiser can meaningfully improve",
      "Compile prompts instead of editing them by hand",
    ],
    prerequisites: ["Python", "Evaluation fundamentals", "Prompting experience"],
    bestFor: ["AI Engineers", "Researchers", "ML Engineers"],
    organizationName: "Stanford NLP",
    priceModel: "free",
    estimatedMinutes: 90,
    publishedAt: "2025-04-16",
    isOfficial: true,
    hasCode: true,
    qualityScore: 88.6,
    editorScore: 90,
    communityScore: 4.4,
    ratingsCount: 142,
    views: 26200,
    saves: 2940,
    clicks: 8400,
    momentum: 0.76,
    metadata: { stars: 21000, language: "Python", license: "MIT" },
  },
  {
    slug: "pydantic-ai",
    title: "Pydantic AI",
    url: "https://github.com/pydantic/pydantic-ai",
    type: "github",
    topics: ["agents", "ai-engineering"],
    difficulty: "intermediate",
    description:
      "An agent framework from the Pydantic team, built around typed, validated structured output and dependency injection.",
    summary:
      "Brings the ergonomics Python engineers already expect to agent building: type-checked responses validated by Pydantic models, dependency injection for testability, streaming support and model-agnostic providers. Deliberately thin rather than all-encompassing.",
    whyItMatters:
      "Typed, validated output is what makes an LLM safe to call from ordinary application code, and this framework treats that as the primary concern.",
    keyTakeaways: [
      "Validated structured output turns model responses into ordinary typed values",
      "Dependency injection makes agents unit-testable without live model calls",
      "Model-agnostic providers keep swapping vendors cheap",
      "A thin framework leaves control flow in your own code, where it is debuggable",
    ],
    whatYouLearn: [
      "Define and validate structured agent outputs with Pydantic",
      "Write tests for agent behaviour without hitting an API",
      "Stream partial results while retaining validation",
    ],
    prerequisites: ["Python and type hints", "Pydantic basics"],
    bestFor: ["Engineers", "AI Engineers"],
    organizationName: "Pydantic",
    priceModel: "free",
    estimatedMinutes: 60,
    publishedAt: "2025-06-05",
    isOfficial: true,
    hasCode: true,
    qualityScore: 87.8,
    communityScore: 4.6,
    ratingsCount: 118,
    views: 24600,
    saves: 2620,
    clicks: 8100,
    momentum: 0.85,
    metadata: { stars: 12000, language: "Python", license: "MIT" },
  },
  {
    slug: "openai-agents-sdk",
    title: "OpenAI Agents SDK",
    url: "https://github.com/openai/openai-agents-python",
    type: "github",
    topics: ["agents", "multi-agent"],
    difficulty: "intermediate",
    description:
      "A small, unopinionated SDK for agents with handoffs, guardrails and built-in tracing.",
    summary:
      "Provides four primitives: agents with instructions and tools, handoffs for delegating between agents, guardrails for validating input and output, and tracing for inspecting runs. Deliberately minimal, with the loop left visible.",
    whyItMatters:
      "It is the reference implementation of multi-agent handoffs from the vendor whose API most teams are already using.",
    keyTakeaways: [
      "Handoffs express delegation more clearly than nested tool calls",
      "Guardrails belong at the boundary, validating both input and output",
      "Built-in tracing makes multi-agent runs debuggable by default",
      "A minimal surface area means less to unlearn when requirements change",
    ],
    whatYouLearn: [
      "Build a multi-agent system with explicit handoffs",
      "Add input and output guardrails to an agent",
      "Trace and debug an agent run end to end",
    ],
    prerequisites: ["Python", "Function calling basics"],
    bestFor: ["AI Engineers", "Engineers"],
    organizationName: "OpenAI",
    priceModel: "free",
    estimatedMinutes: 55,
    publishedAt: "2025-05-08",
    isOfficial: true,
    hasCode: true,
    qualityScore: 86.4,
    communityScore: 4.4,
    ratingsCount: 104,
    views: 27800,
    saves: 2480,
    clicks: 9200,
    momentum: 0.89,
    metadata: { stars: 14000, language: "Python", license: "MIT" },
  },
  {
    slug: "openai-cookbook",
    title: "OpenAI Cookbook",
    url: "https://github.com/openai/openai-cookbook",
    type: "github",
    topics: ["ai-engineering", "prompting"],
    difficulty: "beginner",
    description: "Runnable recipes for common tasks: structured outputs, embeddings, function calling, evaluation and RAG.",
    summary:
      "A large collection of notebooks and guides maintained alongside the API, covering practical patterns from token counting and retrieval to evaluation harnesses and fine-tuning. Updated as API features change.",
    whyItMatters:
      "When you need the current, correct way to do something with the API, the cookbook is more reliable than search results or memory.",
    keyTakeaways: [
      "Recipes are runnable, so they fail loudly when the API changes",
      "Evaluation and embedding notebooks are the most reusable material",
      "Token counting and cost estimation are covered concretely",
      "Patterns transfer to other providers with small changes",
    ],
    whatYouLearn: [
      "Implement structured outputs and function calling correctly",
      "Build embedding and retrieval pipelines that scale",
      "Set up a simple evaluation harness",
    ],
    prerequisites: ["Python", "An API key to run the notebooks"],
    bestFor: ["Beginners", "Engineers", "AI Engineers"],
    organizationName: "OpenAI",
    priceModel: "free",
    estimatedMinutes: 60,
    publishedAt: "2025-06-24",
    isOfficial: true,
    hasCode: true,
    qualityScore: 88.2,
    communityScore: 4.6,
    ratingsCount: 284,
    views: 46200,
    saves: 4180,
    clicks: 15600,
    momentum: 0.5,
    metadata: { stars: 65000, language: "Jupyter Notebook", license: "MIT" },
  },
  {
    slug: "unsloth",
    title: "Unsloth",
    url: "https://github.com/unslothai/unsloth",
    type: "github",
    topics: ["fine-tuning", "quantization"],
    difficulty: "intermediate",
    description:
      "Fine-tune open models roughly twice as fast with substantially less memory, using hand-written kernels and no accuracy loss.",
    summary:
      "Replaces the hot paths of the fine-tuning stack with custom Triton kernels and a manual backward pass, cutting memory use enough to train larger models on a single consumer GPU. Ships Colab notebooks for the popular model families.",
    whyItMatters:
      "It is the practical difference between fine-tuning being a cloud budget item and something you can do on the hardware you already own.",
    keyTakeaways: [
      "Custom kernels deliver large speedups without approximating the computation",
      "Memory savings translate directly into larger context or batch size",
      "Ready-made notebooks remove most of the setup friction",
      "Supported architectures are a subset, so check before planning around it",
    ],
    whatYouLearn: [
      "Fine-tune a modern open model on a single GPU",
      "Trade sequence length, batch size and memory deliberately",
      "Export tuned adapters for local or server inference",
    ],
    prerequisites: ["Python", "LoRA basics", "GPU access"],
    bestFor: ["ML Engineers", "Practitioners"],
    priceModel: "free",
    estimatedMinutes: 70,
    publishedAt: "2025-06-11",
    isOfficial: true,
    hasCode: true,
    qualityScore: 86.6,
    communityScore: 4.7,
    ratingsCount: 156,
    views: 25400,
    saves: 2840,
    clicks: 8600,
    momentum: 0.73,
    metadata: { stars: 44000, language: "Python", license: "Apache-2.0" },
  },
  {
    slug: "ragas",
    title: "Ragas",
    url: "https://github.com/explodinggradients/ragas",
    type: "github",
    topics: ["rag-evaluation", "evaluation"],
    difficulty: "intermediate",
    description:
      "Evaluation framework for RAG pipelines: faithfulness, answer relevance, context precision and recall.",
    summary:
      "Provides reference-free and reference-based metrics that decompose RAG quality into retrieval and generation components, plus synthetic test set generation from your own documents. Integrates with the common frameworks and tracing tools.",
    whyItMatters:
      "It separates retrieval failures from generation failures, which is the distinction that tells you what to fix.",
    keyTakeaways: [
      "Faithfulness and answer relevance measure different, independently fixable problems",
      "Context precision and recall diagnose the retriever specifically",
      "Synthetic test sets are a reasonable starting point when you have no labels",
      "LLM-judged metrics need their own validation against human judgement",
    ],
    whatYouLearn: [
      "Instrument a RAG pipeline with component-level metrics",
      "Generate a starting evaluation set from your documents",
      "Attribute a quality regression to retrieval or generation",
    ],
    prerequisites: ["Python", "A working RAG pipeline"],
    bestFor: ["AI Engineers", "Data Scientists", "Engineers"],
    priceModel: "free",
    estimatedMinutes: 50,
    publishedAt: "2025-04-29",
    isOfficial: true,
    hasCode: true,
    qualityScore: 84.8,
    communityScore: 4.3,
    ratingsCount: 96,
    views: 19800,
    saves: 2060,
    clicks: 6400,
    momentum: 0.8,
    metadata: { stars: 9800, language: "Python", license: "Apache-2.0" },
  },
  {
    slug: "langfuse",
    title: "Langfuse",
    url: "https://github.com/langfuse/langfuse",
    type: "github",
    topics: ["observability", "ai-engineering"],
    difficulty: "intermediate",
    description:
      "Open-source LLM observability: traces, prompt management, evaluation and cost tracking, self-hostable.",
    summary:
      "Captures nested traces of LLM calls with inputs, outputs, latency, token counts and cost, then layers prompt versioning, datasets and evaluation on top. Framework-agnostic SDKs plus native integrations, with a self-hosted deployment option.",
    whyItMatters:
      "Without traces you are debugging a non-deterministic system by guesswork, and self-hosting keeps sensitive prompts inside your own infrastructure.",
    keyTakeaways: [
      "Nested traces show which step in a chain actually failed",
      "Cost and latency per trace surface expensive paths you would not guess",
      "Prompt versioning connects a behaviour change to a specific deploy",
      "Production traces are the best source of evaluation data you will get",
    ],
    whatYouLearn: [
      "Instrument an application with LLM tracing",
      "Turn production traces into evaluation datasets",
      "Track cost and latency per feature rather than per month",
    ],
    prerequisites: ["Application development experience"],
    bestFor: ["Engineers", "AI Engineers"],
    priceModel: "freemium",
    estimatedMinutes: 45,
    publishedAt: "2025-06-02",
    isOfficial: true,
    hasCode: true,
    qualityScore: 87.4,
    editorScore: 88,
    communityScore: 4.6,
    ratingsCount: 132,
    views: 23200,
    saves: 2480,
    clicks: 7600,
    momentum: 0.78,
    metadata: { stars: 14000, language: "TypeScript", license: "MIT" },
  },
  {
    slug: "pgvector",
    title: "pgvector",
    url: "https://github.com/pgvector/pgvector",
    type: "github",
    topics: ["vector-search", "embeddings"],
    difficulty: "intermediate",
    description:
      "Vector similarity search inside Postgres, with exact and approximate indexes and ordinary SQL.",
    summary:
      "Adds a vector column type plus IVFFlat and HNSW index methods to Postgres, supporting cosine, L2 and inner product distance. Vector search composes with joins, filters and transactions like any other query.",
    whyItMatters:
      "For most applications it removes the need for a separate vector database, keeping embeddings in the same transactional store as the rest of the data.",
    keyTakeaways: [
      "Filtering and joining alongside vector search is the decisive advantage over a separate store",
      "HNSW gives better recall and query speed; IVFFlat builds faster and uses less memory",
      "Index parameters trade recall against latency and must be measured, not guessed",
      "Dimensionality directly drives storage and index build cost",
    ],
    whatYouLearn: [
      "Add vector search to an existing Postgres schema",
      "Choose and tune HNSW or IVFFlat for your workload",
      "Combine semantic and relational filtering in one query",
    ],
    prerequisites: ["SQL and Postgres", "Embedding basics"],
    bestFor: ["Engineers", "AI Engineers", "Data Scientists"],
    priceModel: "free",
    estimatedMinutes: 40,
    publishedAt: "2025-05-19",
    isOfficial: true,
    hasCode: true,
    isEditorPick: true,
    editorNote: "The pragmatic default for vector search. Reach for a dedicated vector database only when this stops being enough.",
    qualityScore: 90.8,
    editorScore: 93,
    communityScore: 4.8,
    ratingsCount: 174,
    views: 28600,
    saves: 3240,
    clicks: 9400,
    momentum: 0.66,
    metadata: { stars: 18000, language: "C", license: "PostgreSQL" },
  },
  {
    slug: "faiss",
    title: "FAISS",
    url: "https://github.com/facebookresearch/faiss",
    type: "github",
    topics: ["vector-search", "embeddings"],
    difficulty: "advanced",
    description:
      "The reference library for billion-scale similarity search, with a large family of index structures and GPU support.",
    summary:
      "Implements exact and approximate nearest neighbour search with product quantisation, inverted files, HNSW and composite indexes, on CPU and GPU. The index factory allows precise control over the memory, speed and recall trade-off.",
    whyItMatters:
      "It is the ceiling on what vector search can do, and understanding its index types explains what every higher-level vector database is doing underneath.",
    keyTakeaways: [
      "Product quantisation compresses vectors enough to keep billions in memory",
      "Index choice is a three-way trade between memory, speed and recall",
      "GPU indexes give order-of-magnitude gains on large batch queries",
      "It is a library, not a service: persistence and serving are your problem",
    ],
    whatYouLearn: [
      "Select and construct an index for a given scale and recall target",
      "Measure recall against exhaustive search honestly",
      "Understand the internals of managed vector databases",
    ],
    prerequisites: ["Python or C++", "Nearest neighbour search concepts"],
    bestFor: ["ML Engineers", "Researchers"],
    organizationName: "Meta AI",
    priceModel: "free",
    estimatedMinutes: 70,
    publishedAt: "2025-03-14",
    isOfficial: true,
    hasCode: true,
    qualityScore: 88.6,
    communityScore: 4.5,
    ratingsCount: 118,
    views: 20400,
    saves: 1780,
    clicks: 6200,
    momentum: 0.21,
    metadata: { stars: 36000, language: "C++", license: "MIT" },
  },
  {
    slug: "llm-course-mlabonne",
    title: "LLM Course",
    url: "https://github.com/mlabonne/llm-course",
    type: "github",
    topics: ["llm", "fine-tuning"],
    difficulty: "intermediate",
    description:
      "A curated curriculum with notebooks covering the LLM scientist and LLM engineer tracks, from fine-tuning to deployment.",
    summary:
      "Organises the field into fundamentals, building an LLM, and deploying applications, with Colab notebooks for quantisation, fine-tuning, model merging and evaluation. Roadmap diagrams make the dependencies between topics explicit.",
    whyItMatters:
      "It answers the question of what order to learn things in, which is the hardest part of self-teaching this material.",
    keyTakeaways: [
      "Separating the scientist and engineer tracks clarifies what you can skip",
      "Notebooks run on free Colab tiers for most exercises",
      "Model merging is covered practically, which is rare",
      "Curation is opinionated, which is what makes it useful",
    ],
    whatYouLearn: [
      "Follow a sequenced path through fine-tuning and quantisation",
      "Run quantisation and merging experiments in notebooks",
      "Identify which parts of the field your role requires",
    ],
    prerequisites: ["Python", "Basic machine learning"],
    bestFor: ["Engineers", "Students", "ML Engineers"],
    authorName: "Maxime Labonne",
    priceModel: "free",
    estimatedMinutes: 90,
    publishedAt: "2025-02-24",
    hasCode: true,
    qualityScore: 85.4,
    communityScore: 4.6,
    ratingsCount: 186,
    views: 31200,
    saves: 3520,
    clicks: 9800,
    momentum: 0.54,
    metadata: { stars: 62000, language: "Jupyter Notebook", license: "Apache-2.0" },
  },
  {
    slug: "model-context-protocol-spec",
    title: "Model Context Protocol Specification",
    url: "https://modelcontextprotocol.io/",
    type: "documentation",
    topics: ["mcp", "agents", "tool-use"],
    difficulty: "intermediate",
    description:
      "An open protocol for connecting models to tools, data and prompts, so integrations are written once rather than per client.",
    summary:
      "Specifies a JSON-RPC protocol with three primitives: tools the model can call, resources it can read, and prompts it can be given, over stdio or HTTP transports. Includes SDKs and a growing catalogue of servers.",
    whyItMatters:
      "It turns the N-times-M integration problem into N plus M, and it has been adopted quickly enough across vendors to be a real standard.",
    keyTakeaways: [
      "Tools, resources and prompts are the three primitives worth understanding",
      "One server works with every compliant client, which is the whole point",
      "The transport separation makes local and remote servers interchangeable",
      "Authorisation and trust boundaries are the operator's responsibility",
    ],
    whatYouLearn: [
      "Build an MCP server exposing your own tools and data",
      "Connect a compliant client to local and remote servers",
      "Reason about the security boundary an MCP server sits on",
    ],
    prerequisites: ["JSON-RPC or API design familiarity"],
    bestFor: ["Engineers", "AI Engineers"],
    organizationName: "Anthropic",
    priceModel: "free",
    estimatedMinutes: 50,
    publishedAt: "2025-06-18",
    isOfficial: true,
    hasCode: true,
    isEditorPick: true,
    editorNote: "The integration standard agents are converging on. Learn the three primitives and the ecosystem opens up.",
    qualityScore: 91.4,
    editorScore: 94,
    communityScore: 4.7,
    ratingsCount: 168,
    views: 42800,
    saves: 4680,
    clicks: 14200,
    momentum: 0.96,
    metadata: { transports: ["stdio", "http"], sdks: ["Python", "TypeScript", "Kotlin", "Java"] },
  },
  {
    slug: "openai-structured-outputs-guide",
    title: "Structured Outputs Guide",
    url: "https://platform.openai.com/docs/guides/structured-outputs",
    type: "documentation",
    topics: ["ai-engineering"],
    difficulty: "intermediate",
    description:
      "How to get output that conforms to a JSON Schema every time, using constrained decoding rather than hopeful prompting.",
    summary:
      "Explains strict schema adherence, the supported subset of JSON Schema, refusal handling, and how structured outputs differ from JSON mode. Includes the schema constraints that trip people up in practice.",
    whyItMatters:
      "Guaranteed schema conformance is what makes model output safe to pass into typed application code without defensive parsing.",
    keyTakeaways: [
      "Constrained decoding guarantees the shape; it does not guarantee the content is correct",
      "Only a subset of JSON Schema is supported, and required fields behave specifically",
      "Refusals are a separate response path that must be handled explicitly",
      "Schema design affects output quality, not just validity",
    ],
    whatYouLearn: [
      "Define schemas that the API will accept and enforce",
      "Handle refusals and validation failures properly",
      "Replace defensive JSON parsing with typed values",
    ],
    prerequisites: ["JSON Schema basics", "API integration experience"],
    bestFor: ["Engineers", "AI Engineers"],
    organizationName: "OpenAI",
    priceModel: "free",
    estimatedMinutes: 30,
    publishedAt: "2025-04-22",
    isOfficial: true,
    hasCode: true,
    qualityScore: 86.2,
    communityScore: 4.5,
    ratingsCount: 124,
    views: 26800,
    saves: 2340,
    clicks: 9100,
    momentum: 0.62,
    metadata: { section: "Guides" },
  },
  {
    slug: "anthropic-tool-use-docs",
    title: "Tool Use with Claude",
    url: "https://docs.anthropic.com/en/docs/agents-and-tools/tool-use/overview",
    type: "documentation",
    topics: ["tool-use", "agents"],
    difficulty: "intermediate",
    description:
      "The official guide to defining tools, handling tool calls and running multi-turn tool loops.",
    summary:
      "Covers tool schema definition, the request and response cycle, parallel tool calls, forced tool choice and streaming, with guidance on writing descriptions the model can act on reliably. Includes token cost implications of tool definitions.",
    whyItMatters:
      "Tool descriptions are prompts, and this is the vendor's own account of how to write ones that work.",
    keyTakeaways: [
      "Tool descriptions carry most of the reliability burden and deserve real editing",
      "Parallel tool calls need idempotent handlers",
      "Forcing tool choice is occasionally the right escape hatch",
      "Tool definitions consume context on every request",
    ],
    whatYouLearn: [
      "Define tools with schemas and descriptions that work first time",
      "Implement a correct multi-turn tool loop",
      "Budget context spent on tool definitions",
    ],
    prerequisites: ["API integration experience"],
    bestFor: ["Engineers", "AI Engineers"],
    organizationName: "Anthropic",
    priceModel: "free",
    estimatedMinutes: 35,
    publishedAt: "2025-05-06",
    isOfficial: true,
    hasCode: true,
    qualityScore: 87.6,
    communityScore: 4.6,
    ratingsCount: 108,
    views: 24200,
    saves: 2180,
    clicks: 8400,
    momentum: 0.69,
    metadata: { section: "Agents and tools" },
  },
  {
    slug: "anthropic-building-effective-agents",
    title: "Building Effective Agents",
    url: "https://www.anthropic.com/engineering/building-effective-agents",
    type: "blog",
    topics: ["agents", "multi-agent"],
    difficulty: "intermediate",
    description:
      "Argues for simple, composable workflow patterns over agent frameworks, with the patterns named and diagrammed.",
    summary:
      "Distinguishes workflows, where the path is predefined, from agents, which direct their own process, then presents five patterns: prompt chaining, routing, parallelisation, orchestrator-workers and evaluator-optimiser. Recommends starting with the simplest thing that works and adding autonomy only when it earns its cost.",
    whyItMatters:
      "It is the clearest antidote to framework-first agent design, and its vocabulary has become how practitioners discuss these systems.",
    keyTakeaways: [
      "Most problems labelled agentic are better solved by a fixed workflow",
      "Autonomy costs latency, money and debuggability and must be justified",
      "The five named patterns cover the large majority of real systems",
      "Frameworks obscure the loop you most need to see when debugging",
    ],
    whatYouLearn: [
      "Choose between a workflow and an agent deliberately",
      "Apply the five composition patterns to a real problem",
      "Judge whether a framework is earning its abstraction cost",
    ],
    prerequisites: ["LLM API basics"],
    bestFor: ["Engineers", "AI Engineers", "Product Managers"],
    organizationName: "Anthropic",
    priceModel: "free",
    estimatedMinutes: 22,
    publishedAt: "2024-12-19",
    isOfficial: true,
    isEditorPick: true,
    editorNote: "Read this before you pick an agent framework. Most teams discover they needed a workflow.",
    qualityScore: 94.8,
    editorScore: 97,
    communityScore: 4.9,
    ratingsCount: 342,
    views: 54600,
    saves: 6240,
    clicks: 18200,
    momentum: 0.92,
    metadata: { section: "Engineering" },
  },
  {
    slug: "anthropic-contextual-retrieval",
    title: "Introducing Contextual Retrieval",
    url: "https://www.anthropic.com/news/contextual-retrieval",
    type: "blog",
    topics: ["rag", "chunking", "reranking"],
    difficulty: "intermediate",
    description:
      "Prepending chunk-specific context before embedding cuts retrieval failures substantially, with measurements for each addition.",
    summary:
      "Shows that generating a short contextual preamble for each chunk before embedding reduces retrieval failure by a large margin, and that combining it with BM25 and a reranker compounds the gain. Includes cost analysis made practical by prompt caching.",
    whyItMatters:
      "It is a rare RAG post that reports numbers for each technique separately, so you can decide what to adopt rather than adopting everything.",
    keyTakeaways: [
      "Chunks embedded without surrounding context lose the meaning that made them retrievable",
      "Hybrid keyword and semantic retrieval outperforms either alone",
      "A reranking stage adds further gains on top of better embeddings",
      "Prompt caching makes contextualising every chunk affordable at scale",
    ],
    whatYouLearn: [
      "Implement contextual chunk preambles in an ingestion pipeline",
      "Combine BM25 with embeddings and fuse the rankings",
      "Estimate the one-time cost of better indexing",
    ],
    prerequisites: ["Working RAG pipeline", "Embedding basics"],
    bestFor: ["AI Engineers", "Engineers"],
    organizationName: "Anthropic",
    priceModel: "free",
    estimatedMinutes: 18,
    publishedAt: "2024-09-19",
    isOfficial: true,
    qualityScore: 90.4,
    editorScore: 91,
    communityScore: 4.7,
    ratingsCount: 196,
    views: 34200,
    saves: 3860,
    clicks: 11400,
    momentum: 0.72,
    metadata: { section: "News" },
  },
  {
    slug: "lilian-weng-llm-powered-agents",
    title: "LLM Powered Autonomous Agents",
    url: "https://lilianweng.github.io/posts/2023-06-23-agent/",
    type: "blog",
    topics: ["agents", "agent-memory"],
    difficulty: "intermediate",
    description:
      "The survey that defined the standard agent anatomy: planning, memory, tool use and reflection.",
    summary:
      "Synthesises the agent literature into a single framework covering task decomposition, self-reflection, short and long-term memory with vector stores, and tool use, with citations to the primary work for each component. Includes case studies and a clear-eyed section on limitations.",
    whyItMatters:
      "It is the map of the agent literature, and the component vocabulary nearly every subsequent framework adopted comes from here.",
    keyTakeaways: [
      "Planning, memory, tools and reflection are the four components worth naming",
      "Long-term memory is retrieval over an external store, not a model feature",
      "Reflection loops improve reliability but multiply cost",
      "Finite context and error compounding remain the binding limitations",
    ],
    whatYouLearn: [
      "Decompose an agent design into its four standard components",
      "Trace each idea back to its primary paper",
      "Anticipate where long agent runs break down",
    ],
    prerequisites: ["Prompting basics", "Embeddings"],
    bestFor: ["AI Engineers", "Researchers", "Engineers"],
    authorName: "Lilian Weng",
    priceModel: "free",
    estimatedMinutes: 45,
    publishedAt: "2023-06-23",
    isOfficial: true,
    qualityScore: 92.6,
    editorScore: 93,
    communityScore: 4.8,
    ratingsCount: 268,
    views: 41400,
    saves: 4920,
    clicks: 13600,
    momentum: 0.6,
    metadata: { readingTimeMinutes: 45 },
  },
  {
    slug: "jay-alammar-illustrated-transformer",
    title: "The Illustrated Transformer",
    url: "https://jalammar.github.io/illustrated-transformer/",
    type: "blog",
    topics: ["transformer", "ai-fundamentals"],
    difficulty: "beginner",
    description:
      "The visual explanation of the transformer that most practitioners actually learned it from.",
    summary:
      "Walks through the architecture one diagram at a time: embeddings, query, key and value vectors, multi-head attention, positional encoding, residual connections and the decoder, ending with how the pieces fit together during training.",
    whyItMatters:
      "It converts the original paper's dense notation into something a working engineer can hold in their head, and it has taught more people than any textbook.",
    keyTakeaways: [
      "Query, key and value become intuitive once drawn as matrix operations",
      "Multi-head attention is easiest to grasp visually rather than symbolically",
      "Positional encoding solves a problem you can see in the diagrams",
      "Encoder and decoder differ in a small number of specific ways",
    ],
    whatYouLearn: [
      "Explain the transformer architecture with confidence",
      "Read the original paper without getting stuck on notation",
      "Teach attention to someone else",
    ],
    prerequisites: [],
    bestFor: ["Beginners", "Engineers", "Students"],
    authorName: "Jay Alammar",
    priceModel: "free",
    estimatedMinutes: 30,
    publishedAt: "2018-06-27",
    isOfficial: true,
    isEditorPick: true,
    editorNote: "Still the best on-ramp to attention. Read this, then the paper, in that order.",
    qualityScore: 96.4,
    editorScore: 97,
    communityScore: 4.9,
    ratingsCount: 512,
    views: 72800,
    saves: 7240,
    clicks: 24800,
    momentum: 0.35,
    metadata: { readingTimeMinutes: 30 },
  },
  {
    slug: "eugene-yan-llm-patterns",
    title: "Patterns for Building LLM-based Systems and Products",
    url: "https://eugeneyan.com/writing/llm-patterns/",
    type: "blog",
    topics: ["ai-engineering", "evaluation"],
    difficulty: "intermediate",
    description:
      "Seven practical patterns for LLM systems, ordered from data-centric to user-facing, each with references.",
    summary:
      "Covers evaluation, retrieval augmentation, fine-tuning, caching, guardrails, defensive user experience and collecting user feedback, explaining when each applies and citing the work behind it. Written from production experience rather than demos.",
    whyItMatters:
      "It is the most complete single-page map of the decisions an LLM product team has to make, and it puts evaluation first for the right reasons.",
    keyTakeaways: [
      "Evaluation comes first because every other decision depends on measuring it",
      "Caching is underrated and often the cheapest large win available",
      "Defensive UX design assumes the model will be wrong and plans for it",
      "Feedback collection should be designed into the product, not added later",
    ],
    whatYouLearn: [
      "Sequence the engineering decisions in an LLM product",
      "Apply caching and guardrails where they actually pay off",
      "Design interfaces that collect useful feedback signal",
    ],
    prerequisites: ["Software engineering experience"],
    bestFor: ["AI Engineers", "Engineers", "Product Managers"],
    authorName: "Eugene Yan",
    priceModel: "free",
    estimatedMinutes: 40,
    publishedAt: "2023-07-30",
    isOfficial: true,
    qualityScore: 91.8,
    editorScore: 92,
    communityScore: 4.7,
    ratingsCount: 184,
    views: 29800,
    saves: 3420,
    clicks: 9600,
    momentum: 0.57,
    metadata: { readingTimeMinutes: 40 },
  },
  {
    slug: "hamel-husain-your-ai-product-needs-evals",
    title: "Your AI Product Needs Evals",
    url: "https://hamel.dev/blog/posts/evals/",
    type: "blog",
    topics: ["evaluation", "ai-engineering"],
    difficulty: "intermediate",
    description:
      "How to build an evaluation system that actually improves a product: unit tests, model-graded evals and human review, in a loop.",
    summary:
      "Argues that systematic evaluation, not prompt tinkering, is what separates teams that improve from teams that plateau, then describes a three-level system of assertions, LLM-as-judge and human review, with the data flywheel that connects them.",
    whyItMatters:
      "It is the most practical account of why teams stall on AI products, and the fix is process rather than technology.",
    keyTakeaways: [
      "Simple assertions catch more regressions than people expect",
      "An LLM judge must itself be validated against human labels",
      "Looking at your data is the highest-return activity available",
      "Evaluation, logging and annotation form one loop, not three tools",
    ],
    whatYouLearn: [
      "Build a three-level evaluation system incrementally",
      "Validate an LLM judge against human judgement",
      "Set up the logging and annotation loop that feeds improvement",
    ],
    prerequisites: ["Shipping an LLM feature or wanting to"],
    bestFor: ["AI Engineers", "Product Managers", "Engineers"],
    authorName: "Hamel Husain",
    priceModel: "free",
    estimatedMinutes: 35,
    publishedAt: "2024-03-11",
    isOfficial: true,
    qualityScore: 92.2,
    editorScore: 94,
    communityScore: 4.8,
    ratingsCount: 208,
    views: 31600,
    saves: 3980,
    clicks: 10400,
    momentum: 0.87,
    metadata: { readingTimeMinutes: 35 },
  },
  {
    slug: "chip-huyen-building-llm-applications",
    title: "Building LLM Applications for Production",
    url: "https://huyenchip.com/2023/04/11/llm-engineering.html",
    type: "blog",
    topics: ["ai-engineering", "serving"],
    difficulty: "intermediate",
    description:
      "The engineering challenges of production LLM systems: prompt fragility, cost, latency, and composing tasks into control flow.",
    summary:
      "Catalogues the difficulties of taking LLM prototypes to production, including ambiguous output formats, prompt brittleness under model updates, cost and latency accounting, and building control flow out of task composition. Includes a survey of application patterns.",
    whyItMatters:
      "Written early enough to be prescient and honest enough to still be accurate about where these systems hurt.",
    keyTakeaways: [
      "Prompt brittleness under model updates is a versioning problem, not a wording problem",
      "Cost and latency must be modelled per request, not per month",
      "Control flow assembled from model calls needs the same rigour as any distributed system",
      "Ambiguous output formats are the most common source of production bugs",
    ],
    whatYouLearn: [
      "Anticipate production failure modes before shipping",
      "Version prompts and model choices deliberately",
      "Compose multi-step LLM tasks with explicit control flow",
    ],
    prerequisites: ["Software engineering experience"],
    bestFor: ["Engineers", "AI Engineers", "Founders"],
    authorName: "Chip Huyen",
    priceModel: "free",
    estimatedMinutes: 35,
    publishedAt: "2023-04-11",
    isOfficial: true,
    qualityScore: 89.6,
    communityScore: 4.6,
    ratingsCount: 162,
    views: 27200,
    saves: 2860,
    clicks: 8800,
    momentum: 0.41,
    metadata: { readingTimeMinutes: 35 },
  },
  {
    slug: "simon-willison-prompt-injection",
    title: "Prompt Injection: What's the Worst That Can Happen?",
    url: "https://simonwillison.net/2023/Apr/14/worst-that-can-happen/",
    type: "blog",
    topics: ["llm-safety", "guardrails"],
    difficulty: "intermediate",
    description:
      "Why prompt injection is an architectural problem rather than a filtering problem, with concrete attack scenarios.",
    summary:
      "Explains that concatenating trusted instructions with untrusted content leaves no reliable way for the model to tell them apart, then works through exfiltration and unauthorised action scenarios in assistant products. Argues that mitigation must come from system design and privilege limits.",
    whyItMatters:
      "Any product that gives a model both untrusted input and privileged capabilities inherits this problem, and most teams discover it late.",
    keyTakeaways: [
      "Instructions and data share one channel, so filtering cannot be complete",
      "Combining untrusted content with privileged tools is the dangerous configuration",
      "Data exfiltration through rendered links and images is easy to overlook",
      "Design must assume injection succeeds and limit what it can reach",
    ],
    whatYouLearn: [
      "Identify the injection surface in your own architecture",
      "Apply least privilege to tool access rather than trusting filters",
      "Explain the risk to stakeholders without hand-waving",
    ],
    prerequisites: ["Basic LLM application knowledge"],
    bestFor: ["Engineers", "AI Engineers", "Product Managers"],
    authorName: "Simon Willison",
    priceModel: "free",
    estimatedMinutes: 15,
    publishedAt: "2023-04-14",
    isOfficial: true,
    qualityScore: 89.2,
    editorScore: 91,
    communityScore: 4.7,
    ratingsCount: 146,
    views: 24800,
    saves: 2340,
    clicks: 8200,
    momentum: 0.68,
    metadata: { readingTimeMinutes: 15 },
  },
  {
    slug: "cursor",
    title: "Cursor",
    url: "https://cursor.com",
    type: "ai-product",
    topics: ["ai-coding", "coding-agents"],
    difficulty: "beginner",
    description:
      "An editor built around AI: codebase-aware chat, multi-file edits and an agent that runs commands and iterates.",
    summary:
      "A VS Code-derived editor where model assistance is the primary interface rather than a plugin, with codebase indexing for context, inline and multi-file editing, and an agent mode that can run terminal commands and respond to failures.",
    whyItMatters:
      "It is the clearest demonstration of what changes when AI is designed into the tool instead of bolted on, and it reset expectations for developer tooling.",
    keyTakeaways: [
      "Codebase indexing is what makes suggestions relevant rather than generic",
      "Multi-file editing changes which refactors are worth attempting",
      "Agent mode is most useful with a fast feedback loop such as tests",
      "Rules files let you encode project conventions once",
    ],
    whatYouLearn: [
      "Work effectively with a codebase-aware assistant",
      "Delegate mechanical refactors and verify them quickly",
      "Encode project conventions so the agent follows them",
    ],
    prerequisites: ["Software development experience"],
    bestFor: ["Engineers", "Practitioners", "Founders"],
    organizationName: "Anysphere",
    priceModel: "freemium",
    estimatedMinutes: 30,
    publishedAt: "2025-07-08",
    isOfficial: true,
    qualityScore: 90.2,
    editorScore: 89,
    communityScore: 4.6,
    ratingsCount: 428,
    views: 62400,
    saves: 5480,
    clicks: 21600,
    momentum: 0.91,
    metadata: { platforms: ["macOS", "Windows", "Linux"] },
  },
  {
    slug: "claude-code",
    title: "Claude Code",
    url: "https://www.anthropic.com/claude-code",
    type: "ai-product",
    topics: ["coding-agents", "ai-coding"],
    difficulty: "intermediate",
    description:
      "A terminal-based coding agent that reads your repository, edits files, runs tests and iterates until they pass.",
    summary:
      "Works from the command line with direct access to the filesystem, git and your test suite, handling multi-step tasks such as implementing a feature across files or diagnosing a failing build. Extends through MCP servers and project-level instruction files.",
    whyItMatters:
      "The terminal-native model composes with existing developer workflows and CI in ways an editor plugin cannot.",
    keyTakeaways: [
      "Filesystem and git access let the agent verify its own work",
      "A fast test suite is the single biggest determinant of agent usefulness",
      "Project instruction files carry conventions between sessions",
      "MCP servers extend it to whatever tools your team already uses",
    ],
    whatYouLearn: [
      "Delegate multi-file changes and review the resulting diff",
      "Structure a repository so an agent can work in it effectively",
      "Wire additional tools in through MCP",
    ],
    prerequisites: ["Command line proficiency", "Git"],
    bestFor: ["Engineers", "Practitioners"],
    organizationName: "Anthropic",
    priceModel: "freemium",
    estimatedMinutes: 40,
    publishedAt: "2025-06-25",
    isOfficial: true,
    qualityScore: 89.8,
    communityScore: 4.7,
    ratingsCount: 264,
    views: 48200,
    saves: 4620,
    clicks: 16400,
    momentum: 0.95,
    metadata: { platforms: ["macOS", "Linux", "Windows"] },
  },
  {
    slug: "openrouter",
    title: "OpenRouter",
    url: "https://openrouter.ai/",
    type: "ai-product",
    topics: ["inference", "cost-optimization"],
    difficulty: "beginner",
    description:
      "One OpenAI-compatible API across hundreds of models, with per-model pricing, routing and fallbacks.",
    summary:
      "Proxies requests to many providers behind a single endpoint and key, exposing price and latency per model, automatic fallback when a provider fails, and usage analytics. Model comparison becomes a configuration change rather than an integration project.",
    whyItMatters:
      "It makes model choice reversible, which is the right posture while the frontier moves every few months.",
    keyTakeaways: [
      "A single compatible endpoint removes per-provider integration work",
      "Transparent per-token pricing makes cost comparison straightforward",
      "Automatic fallback improves availability without client changes",
      "It adds a hop, so latency-critical paths should measure the overhead",
    ],
    whatYouLearn: [
      "Compare models on cost and latency for your own workload",
      "Configure routing and fallback policies",
      "Avoid coupling application code to one provider",
    ],
    prerequisites: ["API integration basics"],
    bestFor: ["Engineers", "AI Engineers", "Founders"],
    priceModel: "freemium",
    estimatedMinutes: 25,
    publishedAt: "2025-06-12",
    isOfficial: true,
    qualityScore: 84.6,
    communityScore: 4.5,
    ratingsCount: 148,
    views: 24600,
    saves: 2140,
    clicks: 8800,
    momentum: 0.7,
    metadata: { models: 320 },
  },
  {
    slug: "lmarena",
    title: "LMArena",
    url: "https://lmarena.ai/",
    type: "benchmark",
    topics: ["benchmarks", "evaluation"],
    difficulty: "beginner",
    description:
      "Blind pairwise human voting between models, aggregated into an Elo-style leaderboard.",
    summary:
      "Serves anonymous side-by-side responses from two models and collects human preference votes, aggregating millions of them into ratings with confidence intervals, plus category breakdowns for coding, mathematics and long queries.",
    whyItMatters:
      "It measures the thing static benchmarks cannot, human preference at scale, and it is much harder to contaminate.",
    keyTakeaways: [
      "Blind pairwise comparison avoids brand bias in the vote",
      "Ratings measure preference, which is not the same as correctness",
      "Category breakdowns are more actionable than the overall ranking",
      "Style and formatting influence votes more than people assume",
    ],
    whatYouLearn: [
      "Read preference leaderboards and their confidence intervals correctly",
      "Distinguish preference from capability when choosing a model",
      "Use category rankings for your specific use case",
    ],
    prerequisites: [],
    bestFor: ["Product Managers", "Engineers", "Practitioners"],
    priceModel: "freemium",
    estimatedMinutes: 20,
    publishedAt: "2025-07-01",
    isOfficial: true,
    qualityScore: 85.2,
    communityScore: 4.4,
    ratingsCount: 176,
    views: 28400,
    saves: 1940,
    clicks: 10200,
    momentum: 0.64,
    metadata: { votes: 2400000 },
  },
  {
    slug: "artificial-analysis",
    title: "Artificial Analysis",
    url: "https://artificialanalysis.ai/",
    type: "tool",
    topics: ["benchmarks", "inference", "cost-optimization"],
    difficulty: "beginner",
    description:
      "Independent benchmarks of model quality, speed and price across providers, updated continuously.",
    summary:
      "Measures output tokens per second, time to first token and cost per million tokens for the same models across hosting providers, plotted against quality indices so the trade-offs are visible in one place.",
    whyItMatters:
      "The same model varies substantially in speed and price depending on who serves it, and this is where that difference is actually measured.",
    keyTakeaways: [
      "Provider choice changes latency and cost materially for identical weights",
      "Time to first token and throughput are separate concerns with different fixes",
      "Quality against price plots make the efficient frontier obvious",
      "Measurements shift as providers reconfigure, so the date matters",
    ],
    whatYouLearn: [
      "Choose a hosting provider on measured latency and cost",
      "Reason about the quality, speed and price frontier",
      "Set realistic latency budgets for a product",
    ],
    prerequisites: [],
    bestFor: ["Engineers", "Product Managers", "Founders"],
    priceModel: "freemium",
    estimatedMinutes: 20,
    publishedAt: "2025-07-15",
    isOfficial: true,
    qualityScore: 83.8,
    communityScore: 4.4,
    ratingsCount: 92,
    views: 19200,
    saves: 1620,
    clicks: 6800,
    momentum: 0.67,
    metadata: { providersTracked: 30 },
  },
  {
    slug: "fineweb-dataset",
    title: "FineWeb",
    url: "https://huggingface.co/datasets/HuggingFaceFW/fineweb",
    type: "dataset",
    topics: ["pre-training"],
    difficulty: "advanced",
    description:
      "Fifteen trillion tokens of filtered and deduplicated CommonCrawl, with the filtering decisions published and ablated.",
    summary:
      "An open pre-training corpus built from CommonCrawl with a documented pipeline of language identification, quality filtering and deduplication, each step validated by training small models. The accompanying technical report explains why each filter earns its place.",
    whyItMatters:
      "Pre-training data recipes are usually secret. This one is public, ablated and reproducible, which makes it genuinely educational.",
    keyTakeaways: [
      "Deduplication strategy has a larger effect on quality than most filters",
      "Filter decisions were validated by training ablations, not asserted",
      "The educational subset trades quantity for measurably higher quality",
      "Data curation is where most pre-training quality is actually won",
    ],
    whatYouLearn: [
      "Understand a real pre-training data pipeline end to end",
      "Design ablations that justify a filtering decision",
      "Work with datasets far larger than memory",
    ],
    prerequisites: ["Data engineering experience", "Language model training basics"],
    bestFor: ["Researchers", "ML Engineers"],
    organizationName: "Hugging Face",
    priceModel: "free",
    estimatedMinutes: 60,
    publishedAt: "2024-06-12",
    isOfficial: true,
    qualityScore: 88.4,
    communityScore: 4.6,
    ratingsCount: 64,
    views: 14600,
    saves: 1280,
    clicks: 4400,
    momentum: 0.43,
    metadata: { tokens: "15T", license: "ODC-By-1.0", sizeGb: 43000 },
  },
  {
    slug: "the-batch-newsletter",
    title: "The Batch",
    url: "https://www.deeplearning.ai/the-batch/",
    type: "newsletter",
    topics: ["ai-industry"],
    difficulty: "beginner",
    description:
      "Andrew Ng's weekly newsletter: what happened, why it matters and what it means for practitioners.",
    summary:
      "Each issue opens with a letter from Andrew Ng on a current question, then summarises the week's research and industry news in a consistent what-happened, why-it-matters format. Aimed at practitioners rather than investors.",
    whyItMatters:
      "It is the most reliable way to stay current on an hour a week, with editorial judgement about significance rather than novelty.",
    keyTakeaways: [
      "Consistent structure makes weekly reading fast and skimmable",
      "The opening letter often addresses questions practitioners are actually asking",
      "Research summaries include enough detail to decide whether to read the paper",
      "Coverage is deliberately practitioner-focused rather than market-focused",
    ],
    whatYouLearn: [
      "Track the field without following social media",
      "Judge which papers deserve your reading time",
      "Follow industry developments with practitioner context",
    ],
    prerequisites: [],
    bestFor: ["Beginners", "Engineers", "Product Managers"],
    authorName: "Andrew Ng",
    organizationName: "DeepLearning.AI",
    priceModel: "free",
    estimatedMinutes: 20,
    publishedAt: "2025-07-30",
    isOfficial: true,
    qualityScore: 85.6,
    communityScore: 4.6,
    ratingsCount: 218,
    views: 26800,
    saves: 2340,
    clicks: 8600,
    momentum: 0.37,
    metadata: { cadence: "weekly", subscribers: 900000 },
  },
  {
    slug: "import-ai-newsletter",
    title: "Import AI",
    url: "https://importai.substack.com/",
    type: "newsletter",
    topics: ["ai-industry", "ai-research"],
    difficulty: "intermediate",
    description:
      "Jack Clark's weekly analysis of AI research and policy, with unusually good judgement about what matters.",
    summary:
      "Summarises significant papers with a why-it-matters analysis, tracks policy and governance developments, and closes each issue with a short piece of speculative fiction. Written from inside the policy and research conversation.",
    whyItMatters:
      "It connects technical developments to governance and strategy, a perspective almost no other newsletter provides credibly.",
    keyTakeaways: [
      "Paper summaries emphasise significance over novelty",
      "Policy coverage explains regulation as it is actually being drafted",
      "Willing to state uncertainty rather than manufacture confidence",
      "The fiction sections make long-horizon risks concrete",
    ],
    whatYouLearn: [
      "Follow AI policy alongside technical progress",
      "Assess the strategic significance of a research result",
      "Understand how governance debates are framed",
    ],
    prerequisites: ["Basic AI literacy"],
    bestFor: ["Researchers", "Product Managers", "Founders"],
    authorName: "Jack Clark",
    priceModel: "free",
    estimatedMinutes: 25,
    publishedAt: "2025-07-28",
    isOfficial: true,
    qualityScore: 87.2,
    editorScore: 88,
    communityScore: 4.7,
    ratingsCount: 124,
    views: 17400,
    saves: 1540,
    clicks: 5600,
    momentum: 0.42,
    metadata: { cadence: "weekly" },
  },
  {
    slug: "latent-space-podcast",
    title: "Latent Space",
    url: "https://www.latent.space/",
    type: "podcast",
    topics: ["ai-engineering", "ai-industry"],
    difficulty: "intermediate",
    description:
      "Long-form interviews with the people building AI infrastructure and products, aimed squarely at engineers.",
    summary:
      "Technical conversations with researchers, founders and engineers about how systems are actually built, with detailed show notes and transcripts. Coined and popularised the AI engineer framing of the discipline.",
    whyItMatters:
      "It is where implementation detail that never reaches a blog post gets discussed at length by the people who shipped it.",
    keyTakeaways: [
      "Interviews go deep enough to surface real architectural decisions",
      "Transcripts and notes make episodes searchable and referenceable",
      "Guests are practitioners rather than commentators",
      "Consistent focus on the engineering discipline rather than the discourse",
    ],
    whatYouLearn: [
      "Learn how production AI systems are actually architected",
      "Track the emergence of AI engineering as a role",
      "Hear trade-off discussions that written material omits",
    ],
    prerequisites: ["Software engineering background"],
    bestFor: ["AI Engineers", "Engineers", "Founders"],
    authorName: "Alessio Fanelli and swyx",
    priceModel: "free",
    estimatedMinutes: 75,
    publishedAt: "2025-07-22",
    isOfficial: true,
    qualityScore: 86.4,
    communityScore: 4.6,
    ratingsCount: 142,
    views: 19600,
    saves: 1780,
    clicks: 6200,
    momentum: 0.55,
    metadata: { cadence: "weekly", platform: "Podcast" },
  },
  {
    slug: "dwarkesh-podcast",
    title: "Dwarkesh Podcast",
    url: "https://www.dwarkesh.com/",
    type: "podcast",
    topics: ["ai-industry", "ai-research"],
    difficulty: "beginner",
    description:
      "Unusually well-prepared long-form interviews with AI researchers, lab leaders and historians of technology.",
    summary:
      "Multi-hour conversations distinguished by preparation: the host has read the guest's work closely enough to press on specifics, which produces substantive disagreement rather than press-release answers. Transcripts are published with each episode.",
    whyItMatters:
      "The interviews with lab leadership are among the most informative public sources on how frontier labs actually reason about capability and risk.",
    keyTakeaways: [
      "Preparation is what makes long interviews substantive rather than rambling",
      "Guests are pushed on specifics rather than allowed to stay abstract",
      "Range across research, economics and history gives useful context",
      "Transcripts make the material easy to cite and revisit",
    ],
    whatYouLearn: [
      "Understand how frontier researchers frame progress and risk",
      "Situate AI development in economic and historical context",
      "Hear serious disagreement between informed people",
    ],
    prerequisites: [],
    bestFor: ["Beginners", "Product Managers", "Founders", "Researchers"],
    authorName: "Dwarkesh Patel",
    priceModel: "free",
    estimatedMinutes: 110,
    publishedAt: "2025-07-18",
    isOfficial: true,
    qualityScore: 87.8,
    communityScore: 4.7,
    ratingsCount: 196,
    views: 24200,
    saves: 2060,
    clicks: 7800,
    momentum: 0.59,
    metadata: { cadence: "biweekly", platform: "Podcast" },
  },
];
