import type { SeedPath, SeedRelation, SeedReview } from "./seed-types.ts";

export const seedPaths: SeedPath[] = [
  {
    slug: "ai-fundamentals-from-scratch",
    title: "AI Fundamentals From Scratch",
    subtitle: "From neural network basics to a working GPT you wrote yourself",
    description:
      "A ground-up route for engineers who can code but have never trained a model. You start with visual intuition, build autograd and a small language model by hand, and finish able to read the Transformer paper and follow the architecture in real code.",
    audience: ["Software engineers new to AI", "CS students", "Self-taught developers with Python"],
    outcomes: [
      "Train and evaluate a neural network without copying a template",
      "Implement backpropagation and attention from scratch in PyTorch",
      "Train a character-level GPT on your own text corpus",
      "Read the Transformer paper and map each section to code",
    ],
    difficulty: "beginner",
    estimatedWeeks: 8,
    icon: "graduation-cap",
    accent: "emerald",
    category: "Foundations",
    isPopular: true,
    learnersCount: 12400,
    stages: [
      {
        title: "Build intuition first",
        description: "Get a mental picture of what a network is doing before you meet any of the mathematics.",
        estimatedWeeks: 2,
        resources: ["mit-intro-to-deep-learning", "fast-ai-practical-deep-learning", "3blue1brown-transformers-explained"],
      },
      {
        title: "Code the fundamentals",
        description: "Write autograd, a tokenizer and a small model yourself so no layer stays a black box.",
        estimatedWeeks: 2,
        resources: ["karpathy-neural-networks-zero-to-hero", "hands-on-large-language-models"],
      },
      {
        title: "Understand the Transformer",
        description: "Move from a picture of attention to the original paper and how modern LLMs are trained.",
        estimatedWeeks: 2,
        resources: ["jay-alammar-illustrated-transformer", "attention-is-all-you-need", "karpathy-deep-dive-into-llms"],
      },
      {
        title: "Build a GPT by hand",
        description: "Assemble, train and then compare your own implementation against production-grade code.",
        estimatedWeeks: 2,
        resources: ["karpathy-lets-build-gpt", "nanogpt", "huggingface-transformers"],
      },
    ],
  },
  {
    slug: "llm-application-engineer",
    title: "LLM Application Engineer",
    subtitle: "Go from your first API call to a production LLM feature you can defend",
    description:
      "The flagship path for engineers who need to ship a model-backed feature and keep it healthy. It covers prompting, structured outputs, application patterns, evaluation, observability, serving and cost, so you leave with a feature that is measured rather than vibes-checked.",
    audience: [
      "Backend engineers shipping LLM features",
      "Full-stack engineers adding AI to a product",
      "Tech leads owning an AI roadmap",
    ],
    outcomes: [
      "Ship an LLM feature with typed, schema-validated outputs",
      "Build an offline eval suite that gates every prompt change",
      "Instrument traces, token spend and latency per request",
      "Choose a serving and routing setup with a defensible cost model",
      "Harden a feature against prompt injection and tool misuse",
    ],
    difficulty: "intermediate",
    estimatedWeeks: 10,
    icon: "rocket",
    accent: "indigo",
    category: "Engineering",
    isPopular: true,
    learnersCount: 13800,
    stages: [
      {
        title: "Get fluent with the model API",
        description: "Learn the request surface and the everyday recipes before reaching for any framework.",
        estimatedWeeks: 2,
        resources: ["hugging-face-llm-course", "openai-cookbook", "deeplearning-ai-prompt-engineering"],
      },
      {
        title: "Prompting and structured outputs",
        description: "Turn prompts into reliable, typed interfaces that the rest of your code can trust.",
        estimatedWeeks: 2,
        resources: ["anthropic-prompt-engineering-tutorial", "openai-structured-outputs-guide", "dspy"],
      },
      {
        title: "Application patterns",
        description: "Study the system designs that recur across shipped products and pick the ones you need.",
        estimatedWeeks: 2,
        resources: ["eugene-yan-llm-patterns", "chip-huyen-building-llm-applications", "ai-engineering-book", "langchain"],
      },
      {
        title: "Evaluation and observability",
        description: "Put measurement in place so you can tell an improvement from a regression.",
        estimatedWeeks: 2,
        resources: ["hamel-husain-your-ai-product-needs-evals", "langfuse", "lmarena"],
      },
      {
        title: "Serving, cost and safety",
        description: "Decide where inference runs, what it costs, and how the feature fails safely.",
        estimatedWeeks: 2,
        resources: ["openrouter", "artificial-analysis", "vllm", "simon-willison-prompt-injection"],
      },
    ],
  },
  {
    slug: "rag-systems-in-production",
    title: "RAG Systems in Production",
    subtitle: "Retrieval that survives real corpora, real users and real evaluation",
    description:
      "For engineers whose first retrieval prototype worked in a notebook and then disappointed in production. You work through embeddings, vector indexes, chunking, reranking and contextual retrieval, and end with a measured pipeline instead of an anecdote.",
    audience: ["Backend engineers building search or Q&A", "Data engineers owning a document corpus", "AI engineers past the prototype stage"],
    outcomes: [
      "Ship a RAG service with measured retrieval quality",
      "Choose between Postgres and a dedicated vector index on evidence",
      "Design a chunking and reranking strategy for your own documents",
      "Run a Ragas suite in CI and catch retrieval regressions",
    ],
    difficulty: "intermediate",
    estimatedWeeks: 6,
    icon: "database",
    accent: "cyan",
    category: "Engineering",
    learnersCount: 8600,
    stages: [
      {
        title: "Embeddings and vector search",
        description: "Understand what an embedding encodes and how approximate nearest neighbour search behaves.",
        estimatedWeeks: 2,
        resources: ["hands-on-large-language-models", "pgvector", "faiss"],
      },
      {
        title: "Build the baseline pipeline",
        description: "Stand up the original retrieval-augmented setup end to end before optimising anything.",
        estimatedWeeks: 1,
        resources: ["retrieval-augmented-generation-paper", "llamaindex", "langchain"],
      },
      {
        title: "Chunking, reranking and context",
        description: "Fix the retrieval failures that come from bad splits and mishandled long contexts.",
        estimatedWeeks: 2,
        resources: ["anthropic-contextual-retrieval", "lost-in-the-middle", "eugene-yan-llm-patterns"],
      },
      {
        title: "Measure retrieval quality",
        description: "Replace impressions with recall, faithfulness and traced failures you can act on.",
        estimatedWeeks: 1,
        resources: ["ragas", "hamel-husain-your-ai-product-needs-evals", "langfuse"],
      },
    ],
  },
  {
    slug: "ai-agent-builder",
    title: "AI Agent Builder",
    subtitle: "Tool-using agents that stay reliable once they leave the demo",
    description:
      "A practical route from the ReAct loop to agents that call real tools over MCP and get evaluated like software. It is aimed at engineers who have shipped a prompt-based feature and now need multi-step behaviour they can debug.",
    audience: ["AI engineers building tool-using features", "Backend engineers integrating MCP servers", "Automation-focused product engineers"],
    outcomes: [
      "Implement a ReAct-style loop with tool calls and retries",
      "Expose your own tools through an MCP server",
      "Pick between a single agent and an orchestrated workflow with reasons",
      "Score agent runs on a task suite instead of spot-checking transcripts",
    ],
    difficulty: "intermediate",
    estimatedWeeks: 8,
    icon: "bot",
    accent: "violet",
    category: "Agents",
    learnersCount: 9700,
    stages: [
      {
        title: "How agents reason and act",
        description: "Start from the reasoning traces and the loop that every agent framework is wrapping.",
        estimatedWeeks: 2,
        resources: ["chain-of-thought-prompting", "react-synergizing-reasoning-and-acting", "lilian-weng-llm-powered-agents"],
      },
      {
        title: "Tool use in practice",
        description: "Learn the tool-calling contract and the protocol that makes tools portable across clients.",
        estimatedWeeks: 2,
        resources: ["anthropic-tool-use-docs", "model-context-protocol-spec", "toolformer"],
      },
      {
        title: "Frameworks and orchestration",
        description: "Build with a real framework and see where orchestration helps and where it gets in the way.",
        estimatedWeeks: 2,
        resources: ["hugging-face-agents-course", "pydantic-ai", "openai-agents-sdk", "langchain"],
      },
      {
        title: "Patterns, evaluation and coding agents",
        description: "Adopt the patterns that survive production and measure agents on hard, verifiable tasks.",
        estimatedWeeks: 2,
        resources: ["anthropic-building-effective-agents", "swe-bench", "claude-code", "cursor"],
      },
    ],
  },
  {
    slug: "llm-research-track",
    title: "LLM Research Track",
    subtitle: "Read the primary literature on modern language models in a sensible order",
    description:
      "A reading and coursework track for people who want to contribute to model research rather than consume it. You cover architecture, pre-training and scaling, efficiency, alignment and the reasoning frontier, in the order the field actually built them.",
    audience: ["ML engineers moving toward research", "Graduate students in NLP", "Engineers preparing for pre-training work"],
    outcomes: [
      "Derive and implement attention, and explain each design choice",
      "Size a training run using compute-optimal scaling results",
      "Compare RLHF and direct preference methods on their assumptions",
      "Summarise a new reasoning paper and reproduce its central ablation",
      "Complete a from-scratch language modelling assignment set",
    ],
    difficulty: "advanced",
    estimatedWeeks: 12,
    icon: "microscope",
    accent: "purple",
    category: "Research",
    learnersCount: 2100,
    stages: [
      {
        title: "Architecture foundations",
        description: "Build the theoretical base and the architectural literacy the rest of the track assumes.",
        estimatedWeeks: 3,
        resources: ["attention-is-all-you-need", "stanford-cs224n", "deep-learning-book", "speech-and-language-processing"],
      },
      {
        title: "Pre-training and scaling",
        description: "Learn how data, parameters and compute trade against each other at training time.",
        estimatedWeeks: 3,
        resources: [
          "scaling-laws-for-neural-language-models",
          "chinchilla-compute-optimal-training",
          "fineweb-dataset",
          "stanford-cs336-language-modeling",
        ],
      },
      {
        title: "Efficient architectures",
        description: "See how sparsity and hardware-aware kernels push the frontier without more parameters.",
        estimatedWeeks: 2,
        resources: ["flashattention", "mixtral-of-experts", "llama-3-herd-of-models"],
      },
      {
        title: "Alignment and preference learning",
        description: "Trace the line from human feedback through preference optimisation and AI feedback.",
        estimatedWeeks: 2,
        resources: ["instructgpt-training-with-human-feedback", "direct-preference-optimization", "constitutional-ai"],
      },
      {
        title: "The reasoning frontier",
        description: "Study how test-time reasoning is elicited, trained and measured today.",
        estimatedWeeks: 2,
        resources: ["self-consistency-improves-reasoning", "deepseek-r1-reasoning-via-rl", "mmlu-benchmark"],
      },
    ],
  },
  {
    slug: "fine-tuning-and-optimization",
    title: "Fine-Tuning and Optimization",
    subtitle: "Adapt open models and serve them without wasting a GPU budget",
    description:
      "For engineers who have decided prompting is not enough and now need adapters, quantization and a serving story. You finish able to fine-tune an open model on your own data and defend the inference cost per request.",
    audience: ["ML engineers owning open-weight models", "Platform engineers running GPU inference", "AI engineers hitting prompting limits"],
    outcomes: [
      "Decide between prompting, retrieval and fine-tuning with evidence",
      "Train a LoRA or QLoRA adapter on a single consumer GPU",
      "Quantize a model and quantify the quality it costs you",
      "Serve an open model with continuous batching and measured throughput",
    ],
    difficulty: "advanced",
    estimatedWeeks: 6,
    icon: "sliders",
    accent: "amber",
    category: "Engineering",
    learnersCount: 4200,
    stages: [
      {
        title: "Decide whether to fine-tune",
        description: "Establish what fine-tuning does and does not fix before you rent any hardware.",
        estimatedWeeks: 1,
        resources: ["llm-course-mlabonne", "hugging-face-llm-course", "ai-engineering-book"],
      },
      {
        title: "Parameter-efficient fine-tuning",
        description: "Learn low-rank adaptation from the source papers and then run it on real data.",
        estimatedWeeks: 2,
        resources: ["lora-low-rank-adaptation", "qlora-efficient-finetuning", "unsloth"],
      },
      {
        title: "Quantization and kernels",
        description: "Understand where the memory and the milliseconds actually go during inference.",
        estimatedWeeks: 1,
        resources: ["flashattention", "ollama", "artificial-analysis"],
      },
      {
        title: "Serving and inference economics",
        description: "Turn a trained model into a service with a throughput number and a price per token.",
        estimatedWeeks: 2,
        resources: ["vllm-paged-attention", "vllm", "openrouter"],
      },
    ],
  },
  {
    slug: "ai-product-manager",
    title: "AI Product Manager",
    subtitle: "Enough model literacy to specify, price and evaluate an AI feature",
    description:
      "A short literacy path for product managers and founders who need to make AI decisions without writing the code. It covers what models can do, how to write evals as a product spec, how pricing works, and how to keep up with the landscape.",
    audience: ["Product managers scoping AI features", "Founders evaluating AI bets", "Designers and analysts on AI teams"],
    outcomes: [
      "Explain in plain language what a language model does and where it fails",
      "Write an eval set that serves as the acceptance criteria for a feature",
      "Estimate the token cost of a feature before engineering starts",
      "Run a structured model comparison for a real product decision",
    ],
    difficulty: "beginner",
    estimatedWeeks: 4,
    icon: "compass",
    accent: "rose",
    category: "Career",
    learnersCount: 3400,
    stages: [
      {
        title: "What models can and cannot do",
        description: "Get an accurate mental model of training and inference without any mathematics.",
        estimatedWeeks: 1,
        resources: ["3blue1brown-transformers-explained", "karpathy-deep-dive-into-llms", "the-batch-newsletter"],
      },
      {
        title: "Prompting as a product skill",
        description: "Practise the prompting basics you need to prototype and review a feature yourself.",
        estimatedWeeks: 1,
        resources: ["deeplearning-ai-prompt-engineering", "anthropic-prompt-engineering-tutorial"],
      },
      {
        title: "Evals as the product spec",
        description: "Learn to express quality as a test set that engineering can build against.",
        estimatedWeeks: 1,
        resources: ["hamel-husain-your-ai-product-needs-evals", "lmarena", "mmlu-benchmark"],
      },
      {
        title: "Cost and the landscape",
        description: "Build a working sense of pricing, model choice and where the industry is heading.",
        estimatedWeeks: 1,
        resources: ["artificial-analysis", "openrouter", "latent-space-podcast", "dwarkesh-podcast"],
      },
    ],
  },
];

export const seedRelations: SeedRelation[] = [
  { from: "jay-alammar-illustrated-transformer", to: "attention-is-all-you-need", relation: "explains", weight: 0.95 },
  { from: "3blue1brown-transformers-explained", to: "attention-is-all-you-need", relation: "explains", weight: 0.85 },
  { from: "nanogpt", to: "attention-is-all-you-need", relation: "implements", weight: 0.9 },
  { from: "karpathy-lets-build-gpt", to: "attention-is-all-you-need", relation: "implements", weight: 0.88 },
  { from: "attention-is-all-you-need", to: "flashattention", relation: "prerequisite_of", weight: 0.8 },
  { from: "mit-intro-to-deep-learning", to: "fast-ai-practical-deep-learning", relation: "alternative_to", weight: 0.8 },
  { from: "fast-ai-practical-deep-learning", to: "karpathy-neural-networks-zero-to-hero", relation: "prerequisite_of", weight: 0.75 },
  { from: "karpathy-neural-networks-zero-to-hero", to: "nanogpt", relation: "prerequisite_of", weight: 0.9 },
  { from: "deep-learning-book", to: "speech-and-language-processing", relation: "related_to", weight: 0.5 },
  { from: "stanford-cs224n", to: "stanford-cs336-language-modeling", relation: "prerequisite_of", weight: 0.8 },
  { from: "scaling-laws-for-neural-language-models", to: "chinchilla-compute-optimal-training", relation: "prerequisite_of", weight: 0.9 },
  { from: "chinchilla-compute-optimal-training", to: "llama-3-herd-of-models", relation: "next_step", weight: 0.6 },
  { from: "fineweb-dataset", to: "stanford-cs336-language-modeling", relation: "related_to", weight: 0.55 },
  { from: "karpathy-deep-dive-into-llms", to: "scaling-laws-for-neural-language-models", relation: "explains", weight: 0.5 },
  { from: "instructgpt-training-with-human-feedback", to: "direct-preference-optimization", relation: "prerequisite_of", weight: 0.9 },
  { from: "constitutional-ai", to: "direct-preference-optimization", relation: "alternative_to", weight: 0.55 },
  { from: "chain-of-thought-prompting", to: "self-consistency-improves-reasoning", relation: "prerequisite_of", weight: 0.9 },
  { from: "self-consistency-improves-reasoning", to: "deepseek-r1-reasoning-via-rl", relation: "next_step", weight: 0.6 },
  { from: "chain-of-thought-prompting", to: "deepseek-r1-reasoning-via-rl", relation: "prerequisite_of", weight: 0.7 },
  { from: "direct-preference-optimization", to: "deepseek-r1-reasoning-via-rl", relation: "prerequisite_of", weight: 0.65 },
  { from: "deepseek-r1-reasoning-via-rl", to: "mmlu-benchmark", relation: "related_to", weight: 0.45 },
  { from: "chain-of-thought-prompting", to: "react-synergizing-reasoning-and-acting", relation: "prerequisite_of", weight: 0.9 },
  { from: "lilian-weng-llm-powered-agents", to: "react-synergizing-reasoning-and-acting", relation: "explains", weight: 0.8 },
  { from: "react-synergizing-reasoning-and-acting", to: "anthropic-building-effective-agents", relation: "prerequisite_of", weight: 0.85 },
  { from: "react-synergizing-reasoning-and-acting", to: "toolformer", relation: "next_step", weight: 0.6 },
  { from: "anthropic-tool-use-docs", to: "model-context-protocol-spec", relation: "prerequisite_of", weight: 0.75 },
  { from: "model-context-protocol-spec", to: "anthropic-building-effective-agents", relation: "related_to", weight: 0.7 },
  { from: "model-context-protocol-spec", to: "openai-agents-sdk", relation: "next_step", weight: 0.55 },
  { from: "simon-willison-prompt-injection", to: "model-context-protocol-spec", relation: "related_to", weight: 0.5 },
  { from: "openai-agents-sdk", to: "pydantic-ai", relation: "alternative_to", weight: 0.8 },
  { from: "lilian-weng-llm-powered-agents", to: "anthropic-building-effective-agents", relation: "related_to", weight: 0.7 },
  { from: "claude-code", to: "cursor", relation: "alternative_to", weight: 0.85 },
  { from: "swe-bench", to: "claude-code", relation: "related_to", weight: 0.6 },
  { from: "hands-on-large-language-models", to: "retrieval-augmented-generation-paper", relation: "prerequisite_of", weight: 0.6 },
  { from: "retrieval-augmented-generation-paper", to: "anthropic-contextual-retrieval", relation: "prerequisite_of", weight: 0.8 },
  { from: "retrieval-augmented-generation-paper", to: "lost-in-the-middle", relation: "related_to", weight: 0.65 },
  { from: "llamaindex", to: "retrieval-augmented-generation-paper", relation: "implements", weight: 0.75 },
  { from: "langchain", to: "retrieval-augmented-generation-paper", relation: "implements", weight: 0.6 },
  { from: "langchain", to: "llamaindex", relation: "alternative_to", weight: 0.9 },
  { from: "pgvector", to: "faiss", relation: "alternative_to", weight: 0.85 },
  { from: "anthropic-contextual-retrieval", to: "ragas", relation: "next_step", weight: 0.6 },
  { from: "deeplearning-ai-prompt-engineering", to: "anthropic-prompt-engineering-tutorial", relation: "next_step", weight: 0.7 },
  { from: "anthropic-prompt-engineering-tutorial", to: "dspy", relation: "prerequisite_of", weight: 0.6 },
  { from: "openai-cookbook", to: "openai-structured-outputs-guide", relation: "related_to", weight: 0.65 },
  { from: "eugene-yan-llm-patterns", to: "chip-huyen-building-llm-applications", relation: "related_to", weight: 0.75 },
  { from: "ai-engineering-book", to: "eugene-yan-llm-patterns", relation: "related_to", weight: 0.7 },
  { from: "hamel-husain-your-ai-product-needs-evals", to: "langfuse", relation: "prerequisite_of", weight: 0.6 },
  { from: "hugging-face-llm-course", to: "langchain", relation: "next_step", weight: 0.55 },
  { from: "lora-low-rank-adaptation", to: "qlora-efficient-finetuning", relation: "prerequisite_of", weight: 0.95 },
  { from: "unsloth", to: "lora-low-rank-adaptation", relation: "implements", weight: 0.8 },
  { from: "llm-course-mlabonne", to: "lora-low-rank-adaptation", relation: "explains", weight: 0.65 },
  { from: "huggingface-transformers", to: "unsloth", relation: "prerequisite_of", weight: 0.6 },
  { from: "vllm", to: "vllm-paged-attention", relation: "implements", weight: 0.95 },
  { from: "ollama", to: "vllm", relation: "alternative_to", weight: 0.7 },
  { from: "artificial-analysis", to: "openrouter", relation: "related_to", weight: 0.65 },
  { from: "lmarena", to: "artificial-analysis", relation: "alternative_to", weight: 0.6 },
  { from: "the-batch-newsletter", to: "import-ai-newsletter", relation: "alternative_to", weight: 0.7 },
  { from: "latent-space-podcast", to: "dwarkesh-podcast", relation: "alternative_to", weight: 0.6 },
  { from: "clip-transferable-visual-models", to: "latent-diffusion-models", relation: "prerequisite_of", weight: 0.65 },
  { from: "whisper-robust-speech-recognition", to: "clip-transferable-visual-models", relation: "related_to", weight: 0.4 },
];

export const seedReviews: SeedReview[] = [
  {
    resource: "langchain",
    user: "sierra",
    rating: 3,
    body: "The abstractions move faster than the docs, so I pin versions and read the source whenever a chain misbehaves. It is still the quickest way to wire retrieval and tools together on a deadline.",
  },
  {
    resource: "vllm",
    user: "sierra",
    rating: 5,
    body: "Swapping our homegrown FastAPI wrapper for vLLM halved p95 latency at the same GPU count. PagedAttention and continuous batching are doing real work here, not marketing.",
  },
  {
    resource: "langfuse",
    user: "sierra",
    rating: 5,
    body: "Self-hosting it next to our existing Postgres took an afternoon and gave us per-trace token costs we could put straight on a dashboard. The session view is what finally made prompt regressions visible.",
  },
  {
    resource: "pgvector",
    user: "sierra",
    rating: 4,
    body: "Keeping vectors in the same Postgres as the rest of our data removed an entire service from the on-call rotation. HNSW index builds do get painful past a few million rows.",
  },
  {
    resource: "openai-structured-outputs-guide",
    user: "sierra",
    rating: 4,
    body: "Strict schema mode ended a long run of defensive JSON parsing in our pipeline. Read the section on unsupported schema features before you design your types, it saves a rewrite.",
  },
  {
    resource: "anthropic-building-effective-agents",
    user: "sierra",
    rating: 5,
    body: "The claim that most production wins are plain workflows rather than autonomous loops matches what we learned the expensive way. I now send this to every engineer who wants to add an agent.",
  },
  {
    resource: "simon-willison-prompt-injection",
    user: "sierra",
    rating: 4,
    body: "Short, concrete, and it reframed our threat model: any tool the model can call is reachable by whoever writes the input. We added a tool allowlist the same week we read it.",
  },
  {
    resource: "jay-alammar-illustrated-transformer",
    user: "mira",
    rating: 5,
    body: "The diagrams introduce one moving part at a time, which is why this still outranks newer explainers. If you have ever tried to teach attention on a whiteboard, borrow this ordering.",
  },
  {
    resource: "karpathy-neural-networks-zero-to-hero",
    user: "mira",
    rating: 5,
    body: "Building autograd before touching a framework is the right pedagogical bet, and every video ends with code that runs. Retype it rather than watching straight through, the value is in the typing.",
  },
  {
    resource: "3blue1brown-transformers-explained",
    user: "mira",
    rating: 5,
    body: "Treating embeddings as directions in space gives a beginner a picture they can actually keep. It stops well short of implementation, which is the correct scope for a first exposure.",
  },
  {
    resource: "deep-learning-book",
    user: "mira",
    rating: 3,
    body: "Authoritative and free, but the notation density makes it a reference rather than a course. Chapters six through nine reward the effort if you already have the linear algebra behind you.",
  },
  {
    resource: "hugging-face-llm-course",
    user: "mira",
    rating: 4,
    body: "The exercises are sequenced so each notebook depends on the previous one, which stops learners skipping the tokenizer chapter. A few screenshots lag the current library version.",
  },
  {
    resource: "speech-and-language-processing",
    user: "mira",
    rating: 4,
    body: "Jurafsky and Martin keep the classical NLP grounding that most LLM material now skips, and the draft chapters are revised in the open. Pair it with something hands on.",
  },
  {
    resource: "attention-is-all-you-need",
    user: "devan",
    rating: 5,
    body: "Rereading it after implementing multi-head attention is a different experience: the paper is terse but nothing in it is decorative. The positional encoding section still repays close reading.",
  },
  {
    resource: "chinchilla-compute-optimal-training",
    user: "devan",
    rating: 5,
    body: "The token to parameter ratio changed how we size every training run, and the isoFLOP curves are worth reproducing yourself. Read it immediately after the Kaplan scaling laws paper.",
  },
  {
    resource: "deepseek-r1-reasoning-via-rl",
    user: "devan",
    rating: 5,
    body: "The ablation showing pure reinforcement learning producing long reasoning traces without supervised examples is the most interesting result I read last year. The report is unusually candid about what failed.",
  },
  {
    resource: "flashattention",
    user: "devan",
    rating: 4,
    body: "The IO-aware framing is the real contribution, not the kernel itself, and the memory hierarchy analysis is clean. You want some CUDA background before the tiling details land.",
  },
  {
    resource: "direct-preference-optimization",
    user: "devan",
    rating: 4,
    body: "Deriving the objective from the same reward model assumptions makes the simplification feel earned rather than lucky. In our runs it was less stable than the paper suggests at higher learning rates.",
  },
  {
    resource: "mixtral-of-experts",
    user: "devan",
    rating: 4,
    body: "Worth it for the routing analysis, where experts specialise by token rather than by topic, which was not what I expected. The evaluation table is thinner than the architecture discussion.",
  },
  {
    resource: "nanogpt",
    user: "devan",
    rating: 5,
    body: "A few hundred lines you can hold in your head, and the training script is honest about the hyperparameters it needs. I use it as the baseline whenever I test a new attention variant.",
  },
  {
    resource: "hamel-husain-your-ai-product-needs-evals",
    user: "lena",
    rating: 5,
    body: "Treating error analysis as the first deliverable rather than a later phase reordered our whole roadmap. The argument for reading a hundred traces by hand is the part I quote in planning.",
  },
  {
    resource: "artificial-analysis",
    user: "lena",
    rating: 4,
    body: "Having latency, throughput and price per million tokens on one page settles a lot of internal debate quickly. I still verify the numbers against our own traffic before signing anything.",
  },
  {
    resource: "openrouter",
    user: "lena",
    rating: 4,
    body: "One key across providers let us run a genuine bake off between models before committing to a contract. The fallback routing has quietly saved us during two upstream outages.",
  },
  {
    resource: "lmarena",
    user: "lena",
    rating: 3,
    body: "Useful for a rough public read on model preference, but the leaderboard reflects what voters enjoy rather than what our users need. Treat it as a shortlist, not a decision.",
  },
  {
    resource: "eugene-yan-llm-patterns",
    user: "lena",
    rating: 5,
    body: "This is the closest thing we have to a shared vocabulary for LLM system design, and each pattern arrives with the failure mode it addresses. I keep it open while writing specs.",
  },
  {
    resource: "cursor",
    user: "lena",
    rating: 5,
    body: "The value showed up in refactors rather than greenfield work, where codebase-wide context actually matters. Onboarding a new engineer with it took days off their first ticket.",
  },
  {
    resource: "chip-huyen-building-llm-applications",
    user: "lena",
    rating: 4,
    body: "The section on why latency and cost belong in the product spec, not the postmortem, is the one I share with founders. Some of the tooling references have aged since it was written.",
  },
  {
    resource: "fast-ai-practical-deep-learning",
    user: "kai",
    rating: 5,
    body: "Training a working image classifier in the first lesson kept me going through the parts I did not follow yet. The top-down order felt strange at first and then it clicked.",
  },
  {
    resource: "karpathy-lets-build-gpt",
    user: "kai",
    rating: 4,
    body: "I rewatched the self-attention section four times before it landed, and that felt like a real milestone. Keeping the notebook open beside the video made all the difference for me.",
  },
  {
    resource: "attention-is-all-you-need",
    user: "kai",
    rating: 2,
    body: "I tried this far too early. Without a course behind me the notation and the assumed background made most of it opaque, and I got much more from the illustrated walkthrough first.",
  },
  {
    resource: "anthropic-prompt-engineering-tutorial",
    user: "kai",
    rating: 5,
    body: "Each exercise fails in an obvious way until you fix the prompt, so I learned by getting it wrong repeatedly. It is the first AI resource I finished end to end.",
  },
  {
    resource: "stanford-cs336-language-modeling",
    user: "kai",
    rating: 2,
    body: "The lectures are excellent but the assignments assume you are already comfortable writing training loops from scratch. I stalled on the first one and shelved it until I finish something gentler.",
  },
  {
    resource: "ollama",
    user: "kai",
    rating: 5,
    body: "Running a model locally with one command removed the billing anxiety that was stopping me experimenting. Bigger models crawl on my laptop, but the small ones are enough to learn on.",
  },
];
