import {
  Activity,
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  ArrowUpRight,
  Bookmark,
  BookMarked,
  BookOpen,
  Bot,
  Box,
  Brain,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleDashed,
  Clock,
  Code2,
  Compass,
  Copy,
  Cpu,
  Database,
  DollarSign,
  Eye,
  FileText,
  Filter,
  Flame,
  Gauge,
  GitBranch,
  GitFork,
  GraduationCap,
  Image as ImageIcon,
  LayoutDashboard,
  Layers,
  Link2,
  ListChecks,
  Loader2,
  LogOut,
  Mail,
  Maximize2,
  Menu,
  MessageSquare,
  Mic,
  Microscope,
  Minimize2,
  Monitor,
  Moon,
  Network,
  PenLine,
  Play,
  Plug,
  Plus,
  Quote,
  Repeat,
  Rocket,
  Route,
  Scissors,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Sliders,
  Sparkles,
  Star,
  Sun,
  Terminal,
  TrendingUp,
  Trash2,
  Users,
  Wand2,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";

/**
 * Explicit registry rather than a dynamic lookup: icon names arrive from the
 * database (topics and resource types store their own), and this keeps the
 * bundle tree-shakeable while guaranteeing an unknown name still renders.
 */
const REGISTRY = {
  activity: Activity,
  archive: Archive,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-down": ArrowUpDown,
  "arrow-up-right": ArrowUpRight,
  bookmark: Bookmark,
  "book-marked": BookMarked,
  "book-open": BookOpen,
  bot: Bot,
  box: Box,
  brain: Brain,
  check: Check,
  "check-circle": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  circle: Circle,
  "circle-dashed": CircleDashed,
  clock: Clock,
  code: Code2,
  compass: Compass,
  copy: Copy,
  cpu: Cpu,
  database: Database,
  "dollar-sign": DollarSign,
  eye: Eye,
  "file-text": FileText,
  filter: Filter,
  flame: Flame,
  gauge: Gauge,
  "git-branch": GitBranch,
  github: GitFork,
  "graduation-cap": GraduationCap,
  image: ImageIcon,
  layers: Layers,
  layout: LayoutDashboard,
  link: Link2,
  "list-checks": ListChecks,
  loader: Loader2,
  "log-out": LogOut,
  mail: Mail,
  maximize: Maximize2,
  menu: Menu,
  "message-square": MessageSquare,
  mic: Mic,
  microscope: Microscope,
  minimize: Minimize2,
  monitor: Monitor,
  moon: Moon,
  network: Network,
  "pen-line": PenLine,
  play: Play,
  plug: Plug,
  plus: Plus,
  quote: Quote,
  repeat: Repeat,
  rocket: Rocket,
  route: Route,
  scissors: Scissors,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  "shield-check": ShieldCheck,
  sliders: Sliders,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  terminal: Terminal,
  trash: Trash2,
  "trending-up": TrendingUp,
  users: Users,
  wand: Wand2,
  wrench: Wrench,
  x: X,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof REGISTRY;

export function Icon({
  name,
  className,
  strokeWidth = 2,
}: {
  name: IconName | (string & {});
  className?: string;
  strokeWidth?: number;
}) {
  const Component = REGISTRY[name as IconName] ?? Sparkles;
  return <Component aria-hidden className={cn("size-4 shrink-0", className)} strokeWidth={strokeWidth} />;
}

export function hasIcon(name: string): name is IconName {
  return name in REGISTRY;
}
